/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness/readiness probe
         * @description Returns 200 when the server (and its database, once wired) is healthy.
         */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ping": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Connectivity check */
        get: operations["getPing"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/setup/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * First-run setup status
         * @description Reports whether the instance has no users yet and needs the setup wizard.
         */
        get: operations["getSetupStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/setup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create the first (admin) user
         * @description Allowed only when no user exists yet; creates an administrator and starts a session.
         */
        post: operations["postSetup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Log in */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Log out (revoke the current session) */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current authenticated user */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List users (admin) */
        get: operations["listUsers"];
        put?: never;
        /** Create a user (admin) */
        post: operations["createUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users/{id}/disable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Enable or disable a user (admin) */
        post: operations["setUserDisabled"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users/{id}/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset a user's password (admin) */
        post: operations["resetUserPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/wallets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the current user's wallets */
        get: operations["listWallets"];
        put?: never;
        /** Create a wallet (creator becomes owner) */
        post: operations["createWallet"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/wallets/{walletId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                walletId: number;
            };
            cookie?: never;
        };
        /** Get a wallet */
        get: operations["getWallet"];
        put?: never;
        post?: never;
        /** Delete a wallet and all its data (owner only) */
        delete: operations["deleteWallet"];
        options?: never;
        head?: never;
        /** Rename a wallet (owner only) */
        patch: operations["updateWallet"];
        trace?: never;
    };
    "/api/v1/catalog/currencies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The ISO 4217 currency catalog */
        get: operations["getCurrencyCatalog"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/wallets/{walletId}/currencies": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                walletId: number;
            };
            cookie?: never;
        };
        /** List a wallet's currencies */
        get: operations["listCurrencies"];
        put?: never;
        /** Add a currency to a wallet */
        post: operations["addCurrency"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/wallets/{walletId}/currencies/{currencyId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                walletId: number;
                currencyId: number;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove a currency (not the base) */
        delete: operations["deleteCurrency"];
        options?: never;
        head?: never;
        /** Update a currency's rate and/or formatting */
        patch: operations["updateCurrency"];
        trace?: never;
    };
    "/api/v1/wallets/{walletId}/currencies/{currencyId}/base": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                walletId: number;
                currencyId: number;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Make a currency the wallet's base */
        post: operations["setBaseCurrency"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/wallets/{walletId}/currencies/{currencyId}/rates": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                walletId: number;
                currencyId: number;
            };
            cookie?: never;
        };
        /** A currency's exchange-rate history */
        get: operations["getCurrencyRates"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/wallets/{walletId}/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                walletId: number;
            };
            cookie?: never;
        };
        /** List a wallet's accounts */
        get: operations["listAccounts"];
        put?: never;
        /** Create an account */
        post: operations["createAccount"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/wallets/{walletId}/accounts/reorder": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                walletId: number;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reorder accounts (positions and groups) */
        post: operations["reorderAccounts"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/wallets/{walletId}/accounts/{accountId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                walletId: number;
                accountId: number;
            };
            cookie?: never;
        };
        /** Get an account */
        get: operations["getAccount"];
        put?: never;
        post?: never;
        /** Delete an account and its data */
        delete: operations["deleteAccount"];
        options?: never;
        head?: never;
        /** Update an account */
        patch: operations["updateAccount"];
        trace?: never;
    };
    "/api/v1/wallets/{walletId}/categories": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                walletId: number;
            };
            cookie?: never;
        };
        /** List a wallet's categories (two-level) */
        get: operations["listCategories"];
        put?: never;
        /** Create a category or subcategory */
        post: operations["createCategory"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/wallets/{walletId}/categories/{categoryId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                walletId: number;
                categoryId: number;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a category (optionally reassigning references) */
        delete: operations["deleteCategory"];
        options?: never;
        head?: never;
        /** Rename/retype a category */
        patch: operations["updateCategory"];
        trace?: never;
    };
    "/api/v1/wallets/{walletId}/categories/{categoryId}/usage": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                walletId: number;
                categoryId: number;
            };
            cookie?: never;
        };
        /** Reference counts for a category */
        get: operations["getCategoryUsage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/wallets/{walletId}/categories/{categoryId}/merge": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                walletId: number;
                categoryId: number;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Merge a category into another */
        post: operations["mergeCategory"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/wallets/{walletId}/payees": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                walletId: number;
            };
            cookie?: never;
        };
        /** List a wallet's payees */
        get: operations["listPayees"];
        put?: never;
        /** Create a payee */
        post: operations["createPayee"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/wallets/{walletId}/payees/{payeeId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                walletId: number;
                payeeId: number;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a payee */
        delete: operations["deletePayee"];
        options?: never;
        head?: never;
        /** Update a payee */
        patch: operations["updatePayee"];
        trace?: never;
    };
    "/api/v1/wallets/{walletId}/payees/{payeeId}/merge": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                walletId: number;
                payeeId: number;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Merge a payee into another */
        post: operations["mergePayee"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Health: {
            /** @enum {string} */
            status: "ok" | "unhealthy";
            error?: string;
        };
        Error: {
            error: {
                code: string;
                message: string;
            };
        };
        User: {
            /** Format: int64 */
            id: number;
            username: string;
            email: string;
            isAdmin: boolean;
            locale: string;
            theme: string;
            disabled: boolean;
            createdAt: string;
        };
        Credentials: {
            username: string;
            email?: string;
            password: string;
        };
        CreateUserRequest: {
            username: string;
            email?: string;
            password: string;
            isAdmin?: boolean;
        };
        Wallet: {
            /** Format: int64 */
            id: number;
            title: string;
            ownerName: string;
            /** Format: int64 */
            baseCurrencyId?: number | null;
            /** @enum {string} */
            role: "owner" | "member";
            createdAt: string;
        };
        WalletInput: {
            title: string;
            ownerName?: string;
            /** @description ISO 4217 code for the base currency (create only) */
            baseCurrency?: string;
        };
        CatalogEntry: {
            code: string;
            name: string;
            symbol: string;
            fracDigits: number;
            symbolPrefix: boolean;
        };
        Currency: {
            /** Format: int64 */
            id: number;
            isoCode: string;
            name: string;
            symbol: string;
            symbolPrefix: boolean;
            decimalChar: string;
            groupChar: string;
            fracDigits: number;
            isBase: boolean;
            rate: number;
            rateUpdatedAt?: string;
        };
        AddCurrencyRequest: {
            isoCode: string;
            makeBase?: boolean;
        };
        CurrencyUpdate: {
            rate?: number;
            symbol?: string;
            symbolPrefix?: boolean;
            decimalChar?: string;
            groupChar?: string;
            fracDigits?: number;
        };
        ExchangeRate: {
            date: string;
            rate: number;
            source: string;
        };
        Account: {
            /** Format: int64 */
            id: number;
            name: string;
            /** @enum {string} */
            type: "bank" | "cash" | "checking" | "savings" | "creditcard" | "liability" | "asset" | "investment";
            /** Format: int64 */
            currencyId: number;
            institution?: string;
            number?: string;
            /**
             * Format: int64
             * @description minor units
             */
            initialBalance: number;
            /**
             * Format: int64
             * @description minor units
             */
            minimumBalance: number;
            /**
             * Format: int64
             * @description minor units
             */
            balance: number;
            closed: boolean;
            noSummary?: boolean;
            noBudget?: boolean;
            noReport?: boolean;
            position: number;
            groupName?: string;
            notes?: string;
            website?: string;
            createdAt?: string;
            currencyCode: string;
            currencySymbol: string;
            currencySymbolPrefix: boolean;
            currencyDecimalChar: string;
            currencyGroupChar: string;
            currencyFracDigits: number;
        };
        AccountInput: {
            name: string;
            /** @enum {string} */
            type: "bank" | "cash" | "checking" | "savings" | "creditcard" | "liability" | "asset" | "investment";
            /**
             * Format: int64
             * @description defaults to the wallet base currency
             */
            currencyId?: number;
            institution?: string;
            number?: string;
            /** Format: int64 */
            initialBalance?: number;
            /** Format: int64 */
            minimumBalance?: number;
            closed?: boolean;
            noSummary?: boolean;
            noBudget?: boolean;
            noReport?: boolean;
            groupName?: string;
            notes?: string;
            website?: string;
        };
        Category: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            parentId?: number | null;
            name: string;
            isIncome: boolean;
            noBudget: boolean;
        };
        CategoryInput: {
            name: string;
            /** Format: int64 */
            parentId?: number | null;
            isIncome?: boolean;
            noBudget?: boolean;
        };
        CategoryUsage: {
            /** Format: int64 */
            subcategories: number;
            /** Format: int64 */
            payees: number;
        };
        Payee: {
            /** Format: int64 */
            id: number;
            name: string;
            /** Format: int64 */
            defaultCategoryId?: number | null;
            /** Format: int64 */
            defaultPaymentMode?: number | null;
        };
        PayeeInput: {
            name: string;
            /** Format: int64 */
            defaultCategoryId?: number | null;
            /** Format: int64 */
            defaultPaymentMode?: number | null;
        };
        MergeRequest: {
            /** Format: int64 */
            targetId: number;
        };
    };
    responses: {
        /** @description Invalid request. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Authentication required. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Administrator access required. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Not found. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is healthy. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            /** @description A dependency is unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    getPing: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Pong. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example pong */
                        message: string;
                    };
                };
            };
        };
    };
    getSetupStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Setup status. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        needsSetup: boolean;
                    };
                };
            };
        };
    };
    postSetup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Credentials"];
            };
        };
        responses: {
            /** @description Admin created and logged in. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            400: components["responses"]["BadRequest"];
            /** @description Setup has already been completed. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Credentials"];
            };
        };
        responses: {
            /** @description Logged in. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description Too many attempts. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logged out. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The current user. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listUsers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All users. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    createUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserRequest"];
            };
        };
        responses: {
            /** @description User created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description Username already taken. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    setUserDisabled: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    disabled: boolean;
                };
            };
        };
        responses: {
            /** @description Updated. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    resetUserPassword: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    password: string;
                };
            };
        };
        responses: {
            /** @description Password reset. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    listWallets: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The user's wallets. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Wallet"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createWallet: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WalletInput"];
            };
        };
        responses: {
            /** @description Wallet created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Wallet"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    getWallet: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                walletId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The wallet. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Wallet"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteWallet: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                walletId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    updateWallet: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                walletId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WalletInput"];
            };
        };
        responses: {
            /** @description Updated wallet. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Wallet"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    getCurrencyCatalog: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Catalog entries. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogEntry"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listCurrencies: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                walletId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Currencies (base first). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Currency"][];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    addCurrency: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                walletId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddCurrencyRequest"];
            };
        };
        responses: {
            /** @description Currency added. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Currency"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            /** @description Currency already added. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    deleteCurrency: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                walletId: number;
                currencyId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    updateCurrency: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                walletId: number;
                currencyId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CurrencyUpdate"];
            };
        };
        responses: {
            /** @description Updated currency. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Currency"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    setBaseCurrency: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                walletId: number;
                currencyId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Base currency set. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    getCurrencyRates: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                walletId: number;
                currencyId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Rate history (newest first). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExchangeRate"][];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listAccounts: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                walletId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Accounts (ordered by position/group/name). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Account"][];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    createAccount: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                walletId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AccountInput"];
            };
        };
        responses: {
            /** @description Account created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Account"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            /** @description Account name already used. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    reorderAccounts: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                walletId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: int64 */
                    id: number;
                    position: number;
                    groupName?: string;
                }[];
            };
        };
        responses: {
            /** @description Reordered. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    getAccount: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                walletId: number;
                accountId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The account. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Account"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    deleteAccount: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                walletId: number;
                accountId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    updateAccount: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                walletId: number;
                accountId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AccountInput"];
            };
        };
        responses: {
            /** @description Updated account. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Account"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            /** @description Account name already used. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listCategories: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                walletId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Categories. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"][];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    createCategory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                walletId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoryInput"];
            };
        };
        responses: {
            /** @description Created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"];
                };
            };
            400: components["responses"]["BadRequest"];
            /** @description Duplicate name. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    deleteCategory: {
        parameters: {
            query?: {
                reassignTo?: number;
            };
            header?: never;
            path: {
                walletId: number;
                categoryId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            /** @description Has subcategories. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    updateCategory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                walletId: number;
                categoryId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoryInput"];
            };
        };
        responses: {
            /** @description Updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    getCategoryUsage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                walletId: number;
                categoryId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Usage. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryUsage"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    mergeCategory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                walletId: number;
                categoryId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MergeRequest"];
            };
        };
        responses: {
            /** @description Merged. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    listPayees: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                walletId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Payees. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Payee"][];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    createPayee: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                walletId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PayeeInput"];
            };
        };
        responses: {
            /** @description Created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Payee"];
                };
            };
            400: components["responses"]["BadRequest"];
            /** @description Duplicate name. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    deletePayee: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                walletId: number;
                payeeId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    updatePayee: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                walletId: number;
                payeeId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PayeeInput"];
            };
        };
        responses: {
            /** @description Updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Payee"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    mergePayee: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                walletId: number;
                payeeId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MergeRequest"];
            };
        };
        responses: {
            /** @description Merged. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
}
