// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: 2fa.sql

package db

import (
	"context"
)

const clearUserTOTP = `-- name: ClearUserTOTP :exec
UPDATE users SET totp_secret = '', totp_enabled = 0 WHERE id = ?
`

func (q *Queries) ClearUserTOTP(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, clearUserTOTP, id)
	return err
}

const consumeRecoveryCode = `-- name: ConsumeRecoveryCode :execrows
UPDATE mfa_recovery_codes
SET used_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE user_id = ? AND code_hash = ? AND used_at IS NULL
`

type ConsumeRecoveryCodeParams struct {
	UserID   int64
	CodeHash string
}

func (q *Queries) ConsumeRecoveryCode(ctx context.Context, arg ConsumeRecoveryCodeParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, consumeRecoveryCode, arg.UserID, arg.CodeHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const countUnusedRecoveryCodes = `-- name: CountUnusedRecoveryCodes :one
SELECT COUNT(*) FROM mfa_recovery_codes WHERE user_id = ? AND used_at IS NULL
`

func (q *Queries) CountUnusedRecoveryCodes(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUnusedRecoveryCodes, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteRecoveryCodes = `-- name: DeleteRecoveryCodes :exec
DELETE FROM mfa_recovery_codes WHERE user_id = ?
`

func (q *Queries) DeleteRecoveryCodes(ctx context.Context, userID int64) error {
	_, err := q.db.ExecContext(ctx, deleteRecoveryCodes, userID)
	return err
}

const insertRecoveryCode = `-- name: InsertRecoveryCode :exec
INSERT INTO mfa_recovery_codes (user_id, code_hash) VALUES (?, ?)
`

type InsertRecoveryCodeParams struct {
	UserID   int64
	CodeHash string
}

func (q *Queries) InsertRecoveryCode(ctx context.Context, arg InsertRecoveryCodeParams) error {
	_, err := q.db.ExecContext(ctx, insertRecoveryCode, arg.UserID, arg.CodeHash)
	return err
}

const setUserTOTP = `-- name: SetUserTOTP :exec
UPDATE users SET totp_secret = ?, totp_enabled = ? WHERE id = ?
`

type SetUserTOTPParams struct {
	TotpSecret  string
	TotpEnabled int64
	ID          int64
}

func (q *Queries) SetUserTOTP(ctx context.Context, arg SetUserTOTPParams) error {
	_, err := q.db.ExecContext(ctx, setUserTOTP, arg.TotpSecret, arg.TotpEnabled, arg.ID)
	return err
}
