// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: accounts.sql

package db

import (
	"context"
)

const deleteAccount = `-- name: DeleteAccount :exec
DELETE FROM accounts WHERE id = ?
`

func (q *Queries) DeleteAccount(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteAccount, id)
	return err
}

const getAccount = `-- name: GetAccount :one
SELECT id, wallet_id, name, type, currency_id, institution, number, initial_balance, minimum_balance, closed, no_summary, no_budget, no_report, position, group_name, notes, website, created_at FROM accounts WHERE id = ? LIMIT 1
`

func (q *Queries) GetAccount(ctx context.Context, id int64) (Account, error) {
	row := q.db.QueryRowContext(ctx, getAccount, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.WalletID,
		&i.Name,
		&i.Type,
		&i.CurrencyID,
		&i.Institution,
		&i.Number,
		&i.InitialBalance,
		&i.MinimumBalance,
		&i.Closed,
		&i.NoSummary,
		&i.NoBudget,
		&i.NoReport,
		&i.Position,
		&i.GroupName,
		&i.Notes,
		&i.Website,
		&i.CreatedAt,
	)
	return i, err
}

const insertAccount = `-- name: InsertAccount :one
INSERT INTO accounts (
    wallet_id, name, type, currency_id, institution, number,
    initial_balance, minimum_balance, closed, no_summary, no_budget, no_report,
    position, group_name, notes, website
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, wallet_id, name, type, currency_id, institution, number, initial_balance, minimum_balance, closed, no_summary, no_budget, no_report, position, group_name, notes, website, created_at
`

type InsertAccountParams struct {
	WalletID       int64
	Name           string
	Type           string
	CurrencyID     int64
	Institution    string
	Number         string
	InitialBalance int64
	MinimumBalance int64
	Closed         int64
	NoSummary      int64
	NoBudget       int64
	NoReport       int64
	Position       int64
	GroupName      string
	Notes          string
	Website        string
}

func (q *Queries) InsertAccount(ctx context.Context, arg InsertAccountParams) (Account, error) {
	row := q.db.QueryRowContext(ctx, insertAccount,
		arg.WalletID,
		arg.Name,
		arg.Type,
		arg.CurrencyID,
		arg.Institution,
		arg.Number,
		arg.InitialBalance,
		arg.MinimumBalance,
		arg.Closed,
		arg.NoSummary,
		arg.NoBudget,
		arg.NoReport,
		arg.Position,
		arg.GroupName,
		arg.Notes,
		arg.Website,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.WalletID,
		&i.Name,
		&i.Type,
		&i.CurrencyID,
		&i.Institution,
		&i.Number,
		&i.InitialBalance,
		&i.MinimumBalance,
		&i.Closed,
		&i.NoSummary,
		&i.NoBudget,
		&i.NoReport,
		&i.Position,
		&i.GroupName,
		&i.Notes,
		&i.Website,
		&i.CreatedAt,
	)
	return i, err
}

const listAccountsForWallet = `-- name: ListAccountsForWallet :many
SELECT
    a.id, a.wallet_id, a.name, a.type, a.currency_id, a.institution, a.number, a.initial_balance, a.minimum_balance, a.closed, a.no_summary, a.no_budget, a.no_report, a.position, a.group_name, a.notes, a.website, a.created_at,
    c.iso_code      AS currency_code,
    c.symbol        AS currency_symbol,
    c.symbol_prefix AS currency_symbol_prefix,
    c.decimal_char  AS currency_decimal_char,
    c.group_char    AS currency_group_char,
    c.frac_digits   AS currency_frac_digits
FROM accounts a
JOIN currencies c ON c.id = a.currency_id
WHERE a.wallet_id = ?
ORDER BY a.position, a.group_name, a.name
`

type ListAccountsForWalletRow struct {
	ID                   int64
	WalletID             int64
	Name                 string
	Type                 string
	CurrencyID           int64
	Institution          string
	Number               string
	InitialBalance       int64
	MinimumBalance       int64
	Closed               int64
	NoSummary            int64
	NoBudget             int64
	NoReport             int64
	Position             int64
	GroupName            string
	Notes                string
	Website              string
	CreatedAt            string
	CurrencyCode         string
	CurrencySymbol       string
	CurrencySymbolPrefix int64
	CurrencyDecimalChar  string
	CurrencyGroupChar    string
	CurrencyFracDigits   int64
}

func (q *Queries) ListAccountsForWallet(ctx context.Context, walletID int64) ([]ListAccountsForWalletRow, error) {
	rows, err := q.db.QueryContext(ctx, listAccountsForWallet, walletID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAccountsForWalletRow{}
	for rows.Next() {
		var i ListAccountsForWalletRow
		if err := rows.Scan(
			&i.ID,
			&i.WalletID,
			&i.Name,
			&i.Type,
			&i.CurrencyID,
			&i.Institution,
			&i.Number,
			&i.InitialBalance,
			&i.MinimumBalance,
			&i.Closed,
			&i.NoSummary,
			&i.NoBudget,
			&i.NoReport,
			&i.Position,
			&i.GroupName,
			&i.Notes,
			&i.Website,
			&i.CreatedAt,
			&i.CurrencyCode,
			&i.CurrencySymbol,
			&i.CurrencySymbolPrefix,
			&i.CurrencyDecimalChar,
			&i.CurrencyGroupChar,
			&i.CurrencyFracDigits,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextAccountPosition = `-- name: NextAccountPosition :one
SELECT COALESCE(MAX(position), 0) + 1 FROM accounts WHERE wallet_id = ?
`

func (q *Queries) NextAccountPosition(ctx context.Context, walletID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, nextAccountPosition, walletID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const updateAccount = `-- name: UpdateAccount :exec
UPDATE accounts SET
    name = ?, type = ?, currency_id = ?, institution = ?, number = ?,
    initial_balance = ?, minimum_balance = ?, closed = ?,
    no_summary = ?, no_budget = ?, no_report = ?, group_name = ?, notes = ?, website = ?
WHERE id = ?
`

type UpdateAccountParams struct {
	Name           string
	Type           string
	CurrencyID     int64
	Institution    string
	Number         string
	InitialBalance int64
	MinimumBalance int64
	Closed         int64
	NoSummary      int64
	NoBudget       int64
	NoReport       int64
	GroupName      string
	Notes          string
	Website        string
	ID             int64
}

func (q *Queries) UpdateAccount(ctx context.Context, arg UpdateAccountParams) error {
	_, err := q.db.ExecContext(ctx, updateAccount,
		arg.Name,
		arg.Type,
		arg.CurrencyID,
		arg.Institution,
		arg.Number,
		arg.InitialBalance,
		arg.MinimumBalance,
		arg.Closed,
		arg.NoSummary,
		arg.NoBudget,
		arg.NoReport,
		arg.GroupName,
		arg.Notes,
		arg.Website,
		arg.ID,
	)
	return err
}

const updateAccountPosition = `-- name: UpdateAccountPosition :exec
UPDATE accounts SET position = ?, group_name = ? WHERE id = ?
`

type UpdateAccountPositionParams struct {
	Position  int64
	GroupName string
	ID        int64
}

func (q *Queries) UpdateAccountPosition(ctx context.Context, arg UpdateAccountPositionParams) error {
	_, err := q.db.ExecContext(ctx, updateAccountPosition, arg.Position, arg.GroupName, arg.ID)
	return err
}
