// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ai.sql

package db

import (
	"context"
)

const getAISettings = `-- name: GetAISettings :one
SELECT enabled, base_url, model, api_key FROM ai_settings WHERE user_id = ?
`

type GetAISettingsRow struct {
	Enabled int64
	BaseUrl string
	Model   string
	ApiKey  string
}

func (q *Queries) GetAISettings(ctx context.Context, userID int64) (GetAISettingsRow, error) {
	row := q.db.QueryRowContext(ctx, getAISettings, userID)
	var i GetAISettingsRow
	err := row.Scan(
		&i.Enabled,
		&i.BaseUrl,
		&i.Model,
		&i.ApiKey,
	)
	return i, err
}

const upsertAISettings = `-- name: UpsertAISettings :exec
INSERT INTO ai_settings (user_id, enabled, base_url, model, api_key, updated_at)
VALUES (?, ?, ?, ?, ?, strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
ON CONFLICT (user_id) DO UPDATE SET
    enabled = excluded.enabled, base_url = excluded.base_url,
    model = excluded.model, api_key = excluded.api_key, updated_at = excluded.updated_at
`

type UpsertAISettingsParams struct {
	UserID  int64
	Enabled int64
	BaseUrl string
	Model   string
	ApiKey  string
}

func (q *Queries) UpsertAISettings(ctx context.Context, arg UpsertAISettingsParams) error {
	_, err := q.db.ExecContext(ctx, upsertAISettings,
		arg.UserID,
		arg.Enabled,
		arg.BaseUrl,
		arg.Model,
		arg.ApiKey,
	)
	return err
}
