// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: api_tokens.sql

package db

import (
	"context"
	"database/sql"
)

const deleteAPIToken = `-- name: DeleteAPIToken :execrows
DELETE FROM api_tokens WHERE id = ? AND user_id = ?
`

type DeleteAPITokenParams struct {
	ID     string
	UserID int64
}

func (q *Queries) DeleteAPIToken(ctx context.Context, arg DeleteAPITokenParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteAPIToken, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getAPIToken = `-- name: GetAPIToken :one
SELECT id, user_id, name, scope, prefix, created_at, last_used_at, expires_at FROM api_tokens WHERE id = ? LIMIT 1
`

func (q *Queries) GetAPIToken(ctx context.Context, id string) (ApiToken, error) {
	row := q.db.QueryRowContext(ctx, getAPIToken, id)
	var i ApiToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Scope,
		&i.Prefix,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const insertAPIToken = `-- name: InsertAPIToken :one
INSERT INTO api_tokens (id, user_id, name, scope, prefix, expires_at)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, user_id, name, scope, prefix, created_at, last_used_at, expires_at
`

type InsertAPITokenParams struct {
	ID        string
	UserID    int64
	Name      string
	Scope     string
	Prefix    string
	ExpiresAt sql.NullString
}

func (q *Queries) InsertAPIToken(ctx context.Context, arg InsertAPITokenParams) (ApiToken, error) {
	row := q.db.QueryRowContext(ctx, insertAPIToken,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Scope,
		arg.Prefix,
		arg.ExpiresAt,
	)
	var i ApiToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Scope,
		&i.Prefix,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const listAPITokensForUser = `-- name: ListAPITokensForUser :many
SELECT id, user_id, name, scope, prefix, created_at, last_used_at, expires_at FROM api_tokens WHERE user_id = ? ORDER BY created_at DESC, id
`

func (q *Queries) ListAPITokensForUser(ctx context.Context, userID int64) ([]ApiToken, error) {
	rows, err := q.db.QueryContext(ctx, listAPITokensForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApiToken{}
	for rows.Next() {
		var i ApiToken
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Scope,
			&i.Prefix,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchAPIToken = `-- name: TouchAPIToken :exec
UPDATE api_tokens SET last_used_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now') WHERE id = ?
`

func (q *Queries) TouchAPIToken(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, touchAPIToken, id)
	return err
}
