// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: asset_valuations.sql

package db

import (
	"context"
)

const deleteValuation = `-- name: DeleteValuation :exec
DELETE FROM asset_valuations WHERE id = ?
`

func (q *Queries) DeleteValuation(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteValuation, id)
	return err
}

const getValuation = `-- name: GetValuation :one
SELECT id, account_id, date, value, note FROM asset_valuations WHERE id = ? LIMIT 1
`

func (q *Queries) GetValuation(ctx context.Context, id int64) (AssetValuation, error) {
	row := q.db.QueryRowContext(ctx, getValuation, id)
	var i AssetValuation
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Date,
		&i.Value,
		&i.Note,
	)
	return i, err
}

const insertValuation = `-- name: InsertValuation :one
INSERT INTO asset_valuations (account_id, date, value, note)
VALUES (?, ?, ?, ?)
RETURNING id, account_id, date, value, note
`

type InsertValuationParams struct {
	AccountID int64
	Date      string
	Value     int64
	Note      string
}

func (q *Queries) InsertValuation(ctx context.Context, arg InsertValuationParams) (AssetValuation, error) {
	row := q.db.QueryRowContext(ctx, insertValuation,
		arg.AccountID,
		arg.Date,
		arg.Value,
		arg.Note,
	)
	var i AssetValuation
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Date,
		&i.Value,
		&i.Note,
	)
	return i, err
}

const latestValuationsForWallet = `-- name: LatestValuationsForWallet :many
SELECT v.account_id, v.value
FROM asset_valuations v
JOIN accounts a ON a.id = v.account_id
WHERE a.wallet_id = ?
  AND v.id = (
    SELECT v2.id FROM asset_valuations v2
    WHERE v2.account_id = v.account_id
    ORDER BY v2.date DESC, v2.id DESC
    LIMIT 1
  )
`

type LatestValuationsForWalletRow struct {
	AccountID int64
	Value     int64
}

// The most recent valuation (by date, then id) for each asset account in a wallet;
// used to fold recorded values into net-worth totals.
func (q *Queries) LatestValuationsForWallet(ctx context.Context, walletID int64) ([]LatestValuationsForWalletRow, error) {
	rows, err := q.db.QueryContext(ctx, latestValuationsForWallet, walletID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LatestValuationsForWalletRow{}
	for rows.Next() {
		var i LatestValuationsForWalletRow
		if err := rows.Scan(&i.AccountID, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listValuationsForAccount = `-- name: ListValuationsForAccount :many
SELECT id, account_id, date, value, note FROM asset_valuations WHERE account_id = ? ORDER BY date DESC, id DESC
`

func (q *Queries) ListValuationsForAccount(ctx context.Context, accountID int64) ([]AssetValuation, error) {
	rows, err := q.db.QueryContext(ctx, listValuationsForAccount, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AssetValuation{}
	for rows.Next() {
		var i AssetValuation
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Date,
			&i.Value,
			&i.Note,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateValuation = `-- name: UpdateValuation :exec
UPDATE asset_valuations SET date = ?, value = ?, note = ? WHERE id = ?
`

type UpdateValuationParams struct {
	Date  string
	Value int64
	Note  string
	ID    int64
}

func (q *Queries) UpdateValuation(ctx context.Context, arg UpdateValuationParams) error {
	_, err := q.db.ExecContext(ctx, updateValuation,
		arg.Date,
		arg.Value,
		arg.Note,
		arg.ID,
	)
	return err
}
