// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: assignments.sql

package db

import (
	"context"
	"database/sql"
)

const deleteAssignment = `-- name: DeleteAssignment :exec
DELETE FROM assignments WHERE id = ?
`

func (q *Queries) DeleteAssignment(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteAssignment, id)
	return err
}

const getAssignment = `-- name: GetAssignment :one
SELECT id, wallet_id, position, match_field, match_type, pattern, case_sensitive, set_payee_id, set_category_id, set_payment_mode, apply_on_manual, apply_on_import, created_at FROM assignments WHERE id = ? LIMIT 1
`

func (q *Queries) GetAssignment(ctx context.Context, id int64) (Assignment, error) {
	row := q.db.QueryRowContext(ctx, getAssignment, id)
	var i Assignment
	err := row.Scan(
		&i.ID,
		&i.WalletID,
		&i.Position,
		&i.MatchField,
		&i.MatchType,
		&i.Pattern,
		&i.CaseSensitive,
		&i.SetPayeeID,
		&i.SetCategoryID,
		&i.SetPaymentMode,
		&i.ApplyOnManual,
		&i.ApplyOnImport,
		&i.CreatedAt,
	)
	return i, err
}

const insertAssignment = `-- name: InsertAssignment :one
INSERT INTO assignments (
    wallet_id, position, match_field, match_type, pattern, case_sensitive,
    set_payee_id, set_category_id, set_payment_mode, apply_on_manual, apply_on_import
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, wallet_id, position, match_field, match_type, pattern, case_sensitive, set_payee_id, set_category_id, set_payment_mode, apply_on_manual, apply_on_import, created_at
`

type InsertAssignmentParams struct {
	WalletID       int64
	Position       int64
	MatchField     string
	MatchType      string
	Pattern        string
	CaseSensitive  int64
	SetPayeeID     sql.NullInt64
	SetCategoryID  sql.NullInt64
	SetPaymentMode sql.NullInt64
	ApplyOnManual  int64
	ApplyOnImport  int64
}

func (q *Queries) InsertAssignment(ctx context.Context, arg InsertAssignmentParams) (Assignment, error) {
	row := q.db.QueryRowContext(ctx, insertAssignment,
		arg.WalletID,
		arg.Position,
		arg.MatchField,
		arg.MatchType,
		arg.Pattern,
		arg.CaseSensitive,
		arg.SetPayeeID,
		arg.SetCategoryID,
		arg.SetPaymentMode,
		arg.ApplyOnManual,
		arg.ApplyOnImport,
	)
	var i Assignment
	err := row.Scan(
		&i.ID,
		&i.WalletID,
		&i.Position,
		&i.MatchField,
		&i.MatchType,
		&i.Pattern,
		&i.CaseSensitive,
		&i.SetPayeeID,
		&i.SetCategoryID,
		&i.SetPaymentMode,
		&i.ApplyOnManual,
		&i.ApplyOnImport,
		&i.CreatedAt,
	)
	return i, err
}

const listAssignmentsForWallet = `-- name: ListAssignmentsForWallet :many
SELECT id, wallet_id, position, match_field, match_type, pattern, case_sensitive, set_payee_id, set_category_id, set_payment_mode, apply_on_manual, apply_on_import, created_at FROM assignments WHERE wallet_id = ? ORDER BY position, id
`

func (q *Queries) ListAssignmentsForWallet(ctx context.Context, walletID int64) ([]Assignment, error) {
	rows, err := q.db.QueryContext(ctx, listAssignmentsForWallet, walletID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Assignment{}
	for rows.Next() {
		var i Assignment
		if err := rows.Scan(
			&i.ID,
			&i.WalletID,
			&i.Position,
			&i.MatchField,
			&i.MatchType,
			&i.Pattern,
			&i.CaseSensitive,
			&i.SetPayeeID,
			&i.SetCategoryID,
			&i.SetPaymentMode,
			&i.ApplyOnManual,
			&i.ApplyOnImport,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWalletTransactionsForRules = `-- name: ListWalletTransactionsForRules :many
SELECT t.id, t.account_id, t.date, t.memo, t.payee_id, t.category_id, t.payment_mode,
       COALESCE(p.name, '') AS payee_name
FROM transactions t
LEFT JOIN payees p ON p.id = t.payee_id
WHERE t.wallet_id = ?
ORDER BY t.id
`

type ListWalletTransactionsForRulesRow struct {
	ID          int64
	AccountID   int64
	Date        string
	Memo        string
	PayeeID     sql.NullInt64
	CategoryID  sql.NullInt64
	PaymentMode int64
	PayeeName   string
}

func (q *Queries) ListWalletTransactionsForRules(ctx context.Context, walletID int64) ([]ListWalletTransactionsForRulesRow, error) {
	rows, err := q.db.QueryContext(ctx, listWalletTransactionsForRules, walletID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWalletTransactionsForRulesRow{}
	for rows.Next() {
		var i ListWalletTransactionsForRulesRow
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Date,
			&i.Memo,
			&i.PayeeID,
			&i.CategoryID,
			&i.PaymentMode,
			&i.PayeeName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextAssignmentPosition = `-- name: NextAssignmentPosition :one
SELECT CAST(COALESCE(MAX(position) + 1, 0) AS INTEGER) FROM assignments WHERE wallet_id = ?
`

func (q *Queries) NextAssignmentPosition(ctx context.Context, walletID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, nextAssignmentPosition, walletID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const setAssignmentPosition = `-- name: SetAssignmentPosition :exec
UPDATE assignments SET position = ? WHERE id = ? AND wallet_id = ?
`

type SetAssignmentPositionParams struct {
	Position int64
	ID       int64
	WalletID int64
}

func (q *Queries) SetAssignmentPosition(ctx context.Context, arg SetAssignmentPositionParams) error {
	_, err := q.db.ExecContext(ctx, setAssignmentPosition, arg.Position, arg.ID, arg.WalletID)
	return err
}

const updateAssignment = `-- name: UpdateAssignment :exec
UPDATE assignments SET
    match_field = ?, match_type = ?, pattern = ?, case_sensitive = ?,
    set_payee_id = ?, set_category_id = ?, set_payment_mode = ?,
    apply_on_manual = ?, apply_on_import = ?
WHERE id = ?
`

type UpdateAssignmentParams struct {
	MatchField     string
	MatchType      string
	Pattern        string
	CaseSensitive  int64
	SetPayeeID     sql.NullInt64
	SetCategoryID  sql.NullInt64
	SetPaymentMode sql.NullInt64
	ApplyOnManual  int64
	ApplyOnImport  int64
	ID             int64
}

func (q *Queries) UpdateAssignment(ctx context.Context, arg UpdateAssignmentParams) error {
	_, err := q.db.ExecContext(ctx, updateAssignment,
		arg.MatchField,
		arg.MatchType,
		arg.Pattern,
		arg.CaseSensitive,
		arg.SetPayeeID,
		arg.SetCategoryID,
		arg.SetPaymentMode,
		arg.ApplyOnManual,
		arg.ApplyOnImport,
		arg.ID,
	)
	return err
}
