// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: assignments.sql

package db

import (
	"context"
	"database/sql"
)

const addAssignmentTag = `-- name: AddAssignmentTag :exec
INSERT INTO assignment_tags (assignment_id, tag_id) VALUES (?, ?)
ON CONFLICT DO NOTHING
`

type AddAssignmentTagParams struct {
	AssignmentID int64
	TagID        int64
}

func (q *Queries) AddAssignmentTag(ctx context.Context, arg AddAssignmentTagParams) error {
	_, err := q.db.ExecContext(ctx, addAssignmentTag, arg.AssignmentID, arg.TagID)
	return err
}

const deleteAssignment = `-- name: DeleteAssignment :exec
DELETE FROM assignments WHERE id = ?
`

func (q *Queries) DeleteAssignment(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteAssignment, id)
	return err
}

const deleteAssignmentTags = `-- name: DeleteAssignmentTags :exec
DELETE FROM assignment_tags WHERE assignment_id = ?
`

func (q *Queries) DeleteAssignmentTags(ctx context.Context, assignmentID int64) error {
	_, err := q.db.ExecContext(ctx, deleteAssignmentTags, assignmentID)
	return err
}

const getAssignment = `-- name: GetAssignment :one
SELECT id, wallet_id, position, match_field, match_type, pattern, case_sensitive, set_payee_id, set_category_id, set_payment_mode, apply_on_manual, apply_on_import, created_at, match_account_id, set_info FROM assignments WHERE id = ? LIMIT 1
`

func (q *Queries) GetAssignment(ctx context.Context, id int64) (Assignment, error) {
	row := q.db.QueryRowContext(ctx, getAssignment, id)
	var i Assignment
	err := row.Scan(
		&i.ID,
		&i.WalletID,
		&i.Position,
		&i.MatchField,
		&i.MatchType,
		&i.Pattern,
		&i.CaseSensitive,
		&i.SetPayeeID,
		&i.SetCategoryID,
		&i.SetPaymentMode,
		&i.ApplyOnManual,
		&i.ApplyOnImport,
		&i.CreatedAt,
		&i.MatchAccountID,
		&i.SetInfo,
	)
	return i, err
}

const insertAssignment = `-- name: InsertAssignment :one
INSERT INTO assignments (
    wallet_id, position, match_field, match_type, pattern, case_sensitive, match_account_id,
    set_payee_id, set_category_id, set_payment_mode, set_info, apply_on_manual, apply_on_import
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, wallet_id, position, match_field, match_type, pattern, case_sensitive, set_payee_id, set_category_id, set_payment_mode, apply_on_manual, apply_on_import, created_at, match_account_id, set_info
`

type InsertAssignmentParams struct {
	WalletID       int64
	Position       int64
	MatchField     string
	MatchType      string
	Pattern        string
	CaseSensitive  int64
	MatchAccountID sql.NullInt64
	SetPayeeID     sql.NullInt64
	SetCategoryID  sql.NullInt64
	SetPaymentMode sql.NullInt64
	SetInfo        sql.NullString
	ApplyOnManual  int64
	ApplyOnImport  int64
}

func (q *Queries) InsertAssignment(ctx context.Context, arg InsertAssignmentParams) (Assignment, error) {
	row := q.db.QueryRowContext(ctx, insertAssignment,
		arg.WalletID,
		arg.Position,
		arg.MatchField,
		arg.MatchType,
		arg.Pattern,
		arg.CaseSensitive,
		arg.MatchAccountID,
		arg.SetPayeeID,
		arg.SetCategoryID,
		arg.SetPaymentMode,
		arg.SetInfo,
		arg.ApplyOnManual,
		arg.ApplyOnImport,
	)
	var i Assignment
	err := row.Scan(
		&i.ID,
		&i.WalletID,
		&i.Position,
		&i.MatchField,
		&i.MatchType,
		&i.Pattern,
		&i.CaseSensitive,
		&i.SetPayeeID,
		&i.SetCategoryID,
		&i.SetPaymentMode,
		&i.ApplyOnManual,
		&i.ApplyOnImport,
		&i.CreatedAt,
		&i.MatchAccountID,
		&i.SetInfo,
	)
	return i, err
}

const listAssignmentTagsForWallet = `-- name: ListAssignmentTagsForWallet :many
SELECT at.assignment_id, g.id AS tag_id, g.name
FROM assignment_tags at
JOIN assignments a ON a.id = at.assignment_id
JOIN tags g ON g.id = at.tag_id
WHERE a.wallet_id = ?
ORDER BY at.assignment_id, g.name
`

type ListAssignmentTagsForWalletRow struct {
	AssignmentID int64
	TagID        int64
	Name         string
}

// The tags every rule of the wallet adds, by rule then name.
func (q *Queries) ListAssignmentTagsForWallet(ctx context.Context, walletID int64) ([]ListAssignmentTagsForWalletRow, error) {
	rows, err := q.db.QueryContext(ctx, listAssignmentTagsForWallet, walletID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAssignmentTagsForWalletRow{}
	for rows.Next() {
		var i ListAssignmentTagsForWalletRow
		if err := rows.Scan(&i.AssignmentID, &i.TagID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssignmentsForWallet = `-- name: ListAssignmentsForWallet :many
SELECT id, wallet_id, position, match_field, match_type, pattern, case_sensitive, set_payee_id, set_category_id, set_payment_mode, apply_on_manual, apply_on_import, created_at, match_account_id, set_info FROM assignments WHERE wallet_id = ? ORDER BY position, id
`

func (q *Queries) ListAssignmentsForWallet(ctx context.Context, walletID int64) ([]Assignment, error) {
	rows, err := q.db.QueryContext(ctx, listAssignmentsForWallet, walletID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Assignment{}
	for rows.Next() {
		var i Assignment
		if err := rows.Scan(
			&i.ID,
			&i.WalletID,
			&i.Position,
			&i.MatchField,
			&i.MatchType,
			&i.Pattern,
			&i.CaseSensitive,
			&i.SetPayeeID,
			&i.SetCategoryID,
			&i.SetPaymentMode,
			&i.ApplyOnManual,
			&i.ApplyOnImport,
			&i.CreatedAt,
			&i.MatchAccountID,
			&i.SetInfo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWalletTransactionsForRules = `-- name: ListWalletTransactionsForRules :many
SELECT t.id, t.account_id, t.date, t.memo, t.info, t.payee_id, t.category_id, t.payment_mode,
       COALESCE(p.name, '') AS payee_name,
       CAST(COALESCE((SELECT group_concat(g.name, char(31))
                      FROM transaction_tags tt JOIN tags g ON g.id = tt.tag_id
                      WHERE tt.transaction_id = t.id), '') AS TEXT) AS tag_names
FROM transactions t
LEFT JOIN payees p ON p.id = t.payee_id
WHERE t.wallet_id = ?
ORDER BY t.id
`

type ListWalletTransactionsForRulesRow struct {
	ID          int64
	AccountID   int64
	Date        string
	Memo        string
	Info        string
	PayeeID     sql.NullInt64
	CategoryID  sql.NullInt64
	PaymentMode int64
	PayeeName   string
	TagNames    string
}

// Every transaction with what a rule can read (memo, payee, tags, account) and
// what it can fill in. The tags come joined by the unit separator (char 31),
// which no tag name holds.
func (q *Queries) ListWalletTransactionsForRules(ctx context.Context, walletID int64) ([]ListWalletTransactionsForRulesRow, error) {
	rows, err := q.db.QueryContext(ctx, listWalletTransactionsForRules, walletID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWalletTransactionsForRulesRow{}
	for rows.Next() {
		var i ListWalletTransactionsForRulesRow
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Date,
			&i.Memo,
			&i.Info,
			&i.PayeeID,
			&i.CategoryID,
			&i.PaymentMode,
			&i.PayeeName,
			&i.TagNames,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextAssignmentPosition = `-- name: NextAssignmentPosition :one
SELECT CAST(COALESCE(MAX(position) + 1, 0) AS INTEGER) FROM assignments WHERE wallet_id = ?
`

func (q *Queries) NextAssignmentPosition(ctx context.Context, walletID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, nextAssignmentPosition, walletID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const reassignAssignmentTag = `-- name: ReassignAssignmentTag :exec
UPDATE OR IGNORE assignment_tags SET tag_id = ? WHERE tag_id = ?
`

type ReassignAssignmentTagParams struct {
	TagID   int64
	TagID_2 int64
}

// A tag merge moves the rules too; OR IGNORE skips a rule that already adds
// the target (its row goes away with the source tag).
func (q *Queries) ReassignAssignmentTag(ctx context.Context, arg ReassignAssignmentTagParams) error {
	_, err := q.db.ExecContext(ctx, reassignAssignmentTag, arg.TagID, arg.TagID_2)
	return err
}

const setAssignmentPosition = `-- name: SetAssignmentPosition :exec
UPDATE assignments SET position = ? WHERE id = ? AND wallet_id = ?
`

type SetAssignmentPositionParams struct {
	Position int64
	ID       int64
	WalletID int64
}

func (q *Queries) SetAssignmentPosition(ctx context.Context, arg SetAssignmentPositionParams) error {
	_, err := q.db.ExecContext(ctx, setAssignmentPosition, arg.Position, arg.ID, arg.WalletID)
	return err
}

const updateAssignment = `-- name: UpdateAssignment :exec
UPDATE assignments SET
    match_field = ?, match_type = ?, pattern = ?, case_sensitive = ?, match_account_id = ?,
    set_payee_id = ?, set_category_id = ?, set_payment_mode = ?, set_info = ?,
    apply_on_manual = ?, apply_on_import = ?
WHERE id = ?
`

type UpdateAssignmentParams struct {
	MatchField     string
	MatchType      string
	Pattern        string
	CaseSensitive  int64
	MatchAccountID sql.NullInt64
	SetPayeeID     sql.NullInt64
	SetCategoryID  sql.NullInt64
	SetPaymentMode sql.NullInt64
	SetInfo        sql.NullString
	ApplyOnManual  int64
	ApplyOnImport  int64
	ID             int64
}

func (q *Queries) UpdateAssignment(ctx context.Context, arg UpdateAssignmentParams) error {
	_, err := q.db.ExecContext(ctx, updateAssignment,
		arg.MatchField,
		arg.MatchType,
		arg.Pattern,
		arg.CaseSensitive,
		arg.MatchAccountID,
		arg.SetPayeeID,
		arg.SetCategoryID,
		arg.SetPaymentMode,
		arg.SetInfo,
		arg.ApplyOnManual,
		arg.ApplyOnImport,
		arg.ID,
	)
	return err
}
