// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: attachments.sql

package db

import (
	"context"
)

const deleteAttachment = `-- name: DeleteAttachment :exec
DELETE FROM attachments WHERE id = ?
`

func (q *Queries) DeleteAttachment(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteAttachment, id)
	return err
}

const getAttachment = `-- name: GetAttachment :one
SELECT id, wallet_id, transaction_id, filename, content_type, size, storage_key, created_at FROM attachments WHERE id = ? LIMIT 1
`

func (q *Queries) GetAttachment(ctx context.Context, id int64) (Attachment, error) {
	row := q.db.QueryRowContext(ctx, getAttachment, id)
	var i Attachment
	err := row.Scan(
		&i.ID,
		&i.WalletID,
		&i.TransactionID,
		&i.Filename,
		&i.ContentType,
		&i.Size,
		&i.StorageKey,
		&i.CreatedAt,
	)
	return i, err
}

const insertAttachment = `-- name: InsertAttachment :one
INSERT INTO attachments (wallet_id, transaction_id, filename, content_type, size, storage_key)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, wallet_id, transaction_id, filename, content_type, size, storage_key, created_at
`

type InsertAttachmentParams struct {
	WalletID      int64
	TransactionID int64
	Filename      string
	ContentType   string
	Size          int64
	StorageKey    string
}

func (q *Queries) InsertAttachment(ctx context.Context, arg InsertAttachmentParams) (Attachment, error) {
	row := q.db.QueryRowContext(ctx, insertAttachment,
		arg.WalletID,
		arg.TransactionID,
		arg.Filename,
		arg.ContentType,
		arg.Size,
		arg.StorageKey,
	)
	var i Attachment
	err := row.Scan(
		&i.ID,
		&i.WalletID,
		&i.TransactionID,
		&i.Filename,
		&i.ContentType,
		&i.Size,
		&i.StorageKey,
		&i.CreatedAt,
	)
	return i, err
}

const listAttachmentsForTransaction = `-- name: ListAttachmentsForTransaction :many
SELECT id, wallet_id, transaction_id, filename, content_type, size, storage_key, created_at FROM attachments WHERE transaction_id = ? ORDER BY id
`

func (q *Queries) ListAttachmentsForTransaction(ctx context.Context, transactionID int64) ([]Attachment, error) {
	rows, err := q.db.QueryContext(ctx, listAttachmentsForTransaction, transactionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Attachment{}
	for rows.Next() {
		var i Attachment
		if err := rows.Scan(
			&i.ID,
			&i.WalletID,
			&i.TransactionID,
			&i.Filename,
			&i.ContentType,
			&i.Size,
			&i.StorageKey,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAttachmentsForWallet = `-- name: ListAttachmentsForWallet :many
SELECT id, wallet_id, transaction_id, filename, content_type, size, storage_key, created_at FROM attachments WHERE wallet_id = ? ORDER BY id
`

func (q *Queries) ListAttachmentsForWallet(ctx context.Context, walletID int64) ([]Attachment, error) {
	rows, err := q.db.QueryContext(ctx, listAttachmentsForWallet, walletID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Attachment{}
	for rows.Next() {
		var i Attachment
		if err := rows.Scan(
			&i.ID,
			&i.WalletID,
			&i.TransactionID,
			&i.Filename,
			&i.ContentType,
			&i.Size,
			&i.StorageKey,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
