// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bank_sync.sql

package db

import (
	"context"
	"database/sql"
)

const deleteBankConnection = `-- name: DeleteBankConnection :execrows
DELETE FROM bank_connections WHERE id = ? AND wallet_id = ?
`

type DeleteBankConnectionParams struct {
	ID       int64
	WalletID int64
}

func (q *Queries) DeleteBankConnection(ctx context.Context, arg DeleteBankConnectionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteBankConnection, arg.ID, arg.WalletID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteBankLink = `-- name: DeleteBankLink :exec
DELETE FROM bank_links WHERE connection_id = ? AND external_id = ?
`

type DeleteBankLinkParams struct {
	ConnectionID int64
	ExternalID   string
}

func (q *Queries) DeleteBankLink(ctx context.Context, arg DeleteBankLinkParams) error {
	_, err := q.db.ExecContext(ctx, deleteBankLink, arg.ConnectionID, arg.ExternalID)
	return err
}

const getBankConnection = `-- name: GetBankConnection :one
SELECT id, wallet_id, provider, access_url, name, created_at, last_synced_at, aspsp_name, aspsp_country, valid_until, accounts_json, auto_sync, last_sync_at, last_sync_status, last_sync_message, sync_interval_hours, sync_hour, sync_days FROM bank_connections WHERE id = ? LIMIT 1
`

func (q *Queries) GetBankConnection(ctx context.Context, id int64) (BankConnection, error) {
	row := q.db.QueryRowContext(ctx, getBankConnection, id)
	var i BankConnection
	err := row.Scan(
		&i.ID,
		&i.WalletID,
		&i.Provider,
		&i.AccessUrl,
		&i.Name,
		&i.CreatedAt,
		&i.LastSyncedAt,
		&i.AspspName,
		&i.AspspCountry,
		&i.ValidUntil,
		&i.AccountsJson,
		&i.AutoSync,
		&i.LastSyncAt,
		&i.LastSyncStatus,
		&i.LastSyncMessage,
		&i.SyncIntervalHours,
		&i.SyncHour,
		&i.SyncDays,
	)
	return i, err
}

const insertBankConnection = `-- name: InsertBankConnection :one
INSERT INTO bank_connections (wallet_id, provider, access_url, name)
VALUES (?, ?, ?, ?)
RETURNING id, wallet_id, provider, access_url, name, created_at, last_synced_at, aspsp_name, aspsp_country, valid_until, accounts_json, auto_sync, last_sync_at, last_sync_status, last_sync_message, sync_interval_hours, sync_hour, sync_days
`

type InsertBankConnectionParams struct {
	WalletID  int64
	Provider  string
	AccessUrl string
	Name      string
}

func (q *Queries) InsertBankConnection(ctx context.Context, arg InsertBankConnectionParams) (BankConnection, error) {
	row := q.db.QueryRowContext(ctx, insertBankConnection,
		arg.WalletID,
		arg.Provider,
		arg.AccessUrl,
		arg.Name,
	)
	var i BankConnection
	err := row.Scan(
		&i.ID,
		&i.WalletID,
		&i.Provider,
		&i.AccessUrl,
		&i.Name,
		&i.CreatedAt,
		&i.LastSyncedAt,
		&i.AspspName,
		&i.AspspCountry,
		&i.ValidUntil,
		&i.AccountsJson,
		&i.AutoSync,
		&i.LastSyncAt,
		&i.LastSyncStatus,
		&i.LastSyncMessage,
		&i.SyncIntervalHours,
		&i.SyncHour,
		&i.SyncDays,
	)
	return i, err
}

const insertBankSyncRun = `-- name: InsertBankSyncRun :exec
INSERT INTO bank_sync_runs (connection_id, ran_at, triggered_by, status, imported, reconciled, message, accounts_json)
VALUES (?, strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), ?, ?, ?, ?, ?, ?)
`

type InsertBankSyncRunParams struct {
	ConnectionID int64
	TriggeredBy  string
	Status       string
	Imported     int64
	Reconciled   int64
	Message      string
	AccountsJson string
}

func (q *Queries) InsertBankSyncRun(ctx context.Context, arg InsertBankSyncRunParams) error {
	_, err := q.db.ExecContext(ctx, insertBankSyncRun,
		arg.ConnectionID,
		arg.TriggeredBy,
		arg.Status,
		arg.Imported,
		arg.Reconciled,
		arg.Message,
		arg.AccountsJson,
	)
	return err
}

const listAutoSyncConnections = `-- name: ListAutoSyncConnections :many
SELECT id, wallet_id, sync_hour, sync_days, last_synced_at FROM bank_connections
WHERE auto_sync = 1
ORDER BY last_synced_at IS NOT NULL, last_synced_at, id
`

type ListAutoSyncConnectionsRow struct {
	ID           int64
	WalletID     int64
	SyncHour     int64
	SyncDays     int64
	LastSyncedAt sql.NullString
}

// Every connection with auto-sync on, plus its schedule (hour + weekday bitmask)
// and last successful sync. The caller decides which are due for the current time
// in Go, so the day/hour arithmetic stays testable and out of SQL.
func (q *Queries) ListAutoSyncConnections(ctx context.Context) ([]ListAutoSyncConnectionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAutoSyncConnections)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAutoSyncConnectionsRow{}
	for rows.Next() {
		var i ListAutoSyncConnectionsRow
		if err := rows.Scan(
			&i.ID,
			&i.WalletID,
			&i.SyncHour,
			&i.SyncDays,
			&i.LastSyncedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBankConnectionsForWallet = `-- name: ListBankConnectionsForWallet :many
SELECT id, wallet_id, provider, access_url, name, created_at, last_synced_at, aspsp_name, aspsp_country, valid_until, accounts_json, auto_sync, last_sync_at, last_sync_status, last_sync_message, sync_interval_hours, sync_hour, sync_days FROM bank_connections WHERE wallet_id = ? ORDER BY created_at DESC, id
`

func (q *Queries) ListBankConnectionsForWallet(ctx context.Context, walletID int64) ([]BankConnection, error) {
	rows, err := q.db.QueryContext(ctx, listBankConnectionsForWallet, walletID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BankConnection{}
	for rows.Next() {
		var i BankConnection
		if err := rows.Scan(
			&i.ID,
			&i.WalletID,
			&i.Provider,
			&i.AccessUrl,
			&i.Name,
			&i.CreatedAt,
			&i.LastSyncedAt,
			&i.AspspName,
			&i.AspspCountry,
			&i.ValidUntil,
			&i.AccountsJson,
			&i.AutoSync,
			&i.LastSyncAt,
			&i.LastSyncStatus,
			&i.LastSyncMessage,
			&i.SyncIntervalHours,
			&i.SyncHour,
			&i.SyncDays,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBankLinks = `-- name: ListBankLinks :many
SELECT external_id, account_id FROM bank_links WHERE connection_id = ?
`

type ListBankLinksRow struct {
	ExternalID string
	AccountID  int64
}

func (q *Queries) ListBankLinks(ctx context.Context, connectionID int64) ([]ListBankLinksRow, error) {
	rows, err := q.db.QueryContext(ctx, listBankLinks, connectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBankLinksRow{}
	for rows.Next() {
		var i ListBankLinksRow
		if err := rows.Scan(&i.ExternalID, &i.AccountID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBankSyncRuns = `-- name: ListBankSyncRuns :many
SELECT id, connection_id, ran_at, triggered_by, status, imported, reconciled, message, accounts_json FROM bank_sync_runs WHERE connection_id = ? ORDER BY id DESC LIMIT ?
`

type ListBankSyncRunsParams struct {
	ConnectionID int64
	Limit        int64
}

func (q *Queries) ListBankSyncRuns(ctx context.Context, arg ListBankSyncRunsParams) ([]BankSyncRun, error) {
	rows, err := q.db.QueryContext(ctx, listBankSyncRuns, arg.ConnectionID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BankSyncRun{}
	for rows.Next() {
		var i BankSyncRun
		if err := rows.Scan(
			&i.ID,
			&i.ConnectionID,
			&i.RanAt,
			&i.TriggeredBy,
			&i.Status,
			&i.Imported,
			&i.Reconciled,
			&i.Message,
			&i.AccountsJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneBankSyncRuns = `-- name: PruneBankSyncRuns :exec
DELETE FROM bank_sync_runs
WHERE bank_sync_runs.connection_id = ?
  AND bank_sync_runs.id NOT IN (
    SELECT r.id FROM bank_sync_runs r WHERE r.connection_id = ? ORDER BY r.id DESC LIMIT ?
  )
`

type PruneBankSyncRunsParams struct {
	ConnectionID   int64
	ConnectionID_2 int64
	Limit          int64
}

func (q *Queries) PruneBankSyncRuns(ctx context.Context, arg PruneBankSyncRunsParams) error {
	_, err := q.db.ExecContext(ctx, pruneBankSyncRuns, arg.ConnectionID, arg.ConnectionID_2, arg.Limit)
	return err
}

const recordBankSyncOutcome = `-- name: RecordBankSyncOutcome :exec
UPDATE bank_connections
SET last_sync_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now'),
    last_sync_status = ?, last_sync_message = ?
WHERE id = ?
`

type RecordBankSyncOutcomeParams struct {
	LastSyncStatus  string
	LastSyncMessage string
	ID              int64
}

func (q *Queries) RecordBankSyncOutcome(ctx context.Context, arg RecordBankSyncOutcomeParams) error {
	_, err := q.db.ExecContext(ctx, recordBankSyncOutcome, arg.LastSyncStatus, arg.LastSyncMessage, arg.ID)
	return err
}

const setBankConnectionAutoSync = `-- name: SetBankConnectionAutoSync :execrows
UPDATE bank_connections SET auto_sync = ? WHERE id = ? AND wallet_id = ?
`

type SetBankConnectionAutoSyncParams struct {
	AutoSync int64
	ID       int64
	WalletID int64
}

func (q *Queries) SetBankConnectionAutoSync(ctx context.Context, arg SetBankConnectionAutoSyncParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setBankConnectionAutoSync, arg.AutoSync, arg.ID, arg.WalletID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setBankConnectionSchedule = `-- name: SetBankConnectionSchedule :execrows
UPDATE bank_connections SET sync_hour = ?, sync_days = ? WHERE id = ? AND wallet_id = ?
`

type SetBankConnectionScheduleParams struct {
	SyncHour int64
	SyncDays int64
	ID       int64
	WalletID int64
}

func (q *Queries) SetBankConnectionSchedule(ctx context.Context, arg SetBankConnectionScheduleParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setBankConnectionSchedule,
		arg.SyncHour,
		arg.SyncDays,
		arg.ID,
		arg.WalletID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const touchBankConnection = `-- name: TouchBankConnection :exec
UPDATE bank_connections SET last_synced_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now') WHERE id = ?
`

func (q *Queries) TouchBankConnection(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, touchBankConnection, id)
	return err
}

const upsertBankLink = `-- name: UpsertBankLink :exec
INSERT INTO bank_links (connection_id, external_id, account_id)
VALUES (?, ?, ?)
ON CONFLICT (connection_id, external_id) DO UPDATE SET account_id = excluded.account_id
`

type UpsertBankLinkParams struct {
	ConnectionID int64
	ExternalID   string
	AccountID    int64
}

func (q *Queries) UpsertBankLink(ctx context.Context, arg UpsertBankLinkParams) error {
	_, err := q.db.ExecContext(ctx, upsertBankLink, arg.ConnectionID, arg.ExternalID, arg.AccountID)
	return err
}
