// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bank_enablebanking.sql

package db

import (
	"context"
)

const deleteEBankingAuth = `-- name: DeleteEBankingAuth :exec
DELETE FROM bank_ebanking_auth WHERE state = ?
`

func (q *Queries) DeleteEBankingAuth(ctx context.Context, state string) error {
	_, err := q.db.ExecContext(ctx, deleteEBankingAuth, state)
	return err
}

const deleteEBankingConfig = `-- name: DeleteEBankingConfig :execrows
DELETE FROM bank_ebanking_config WHERE wallet_id = ?
`

func (q *Queries) DeleteEBankingConfig(ctx context.Context, walletID int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteEBankingConfig, walletID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getEBankingAuth = `-- name: GetEBankingAuth :one
SELECT state, wallet_id, aspsp_name, aspsp_country, name, redirect_url, created_at FROM bank_ebanking_auth WHERE state = ? LIMIT 1
`

func (q *Queries) GetEBankingAuth(ctx context.Context, state string) (BankEbankingAuth, error) {
	row := q.db.QueryRowContext(ctx, getEBankingAuth, state)
	var i BankEbankingAuth
	err := row.Scan(
		&i.State,
		&i.WalletID,
		&i.AspspName,
		&i.AspspCountry,
		&i.Name,
		&i.RedirectUrl,
		&i.CreatedAt,
	)
	return i, err
}

const getEBankingConfig = `-- name: GetEBankingConfig :one
SELECT wallet_id, app_id, private_key, environment, created_at, updated_at FROM bank_ebanking_config WHERE wallet_id = ? LIMIT 1
`

func (q *Queries) GetEBankingConfig(ctx context.Context, walletID int64) (BankEbankingConfig, error) {
	row := q.db.QueryRowContext(ctx, getEBankingConfig, walletID)
	var i BankEbankingConfig
	err := row.Scan(
		&i.WalletID,
		&i.AppID,
		&i.PrivateKey,
		&i.Environment,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertEBankingAuth = `-- name: InsertEBankingAuth :exec
INSERT INTO bank_ebanking_auth (state, wallet_id, aspsp_name, aspsp_country, name, redirect_url)
VALUES (?, ?, ?, ?, ?, ?)
`

type InsertEBankingAuthParams struct {
	State        string
	WalletID     int64
	AspspName    string
	AspspCountry string
	Name         string
	RedirectUrl  string
}

func (q *Queries) InsertEBankingAuth(ctx context.Context, arg InsertEBankingAuthParams) error {
	_, err := q.db.ExecContext(ctx, insertEBankingAuth,
		arg.State,
		arg.WalletID,
		arg.AspspName,
		arg.AspspCountry,
		arg.Name,
		arg.RedirectUrl,
	)
	return err
}

const insertEBankingConnection = `-- name: InsertEBankingConnection :one
INSERT INTO bank_connections (wallet_id, provider, access_url, name, aspsp_name, aspsp_country, valid_until)
VALUES (?, 'enablebanking', ?, ?, ?, ?, ?)
RETURNING id, wallet_id, provider, access_url, name, created_at, last_synced_at, aspsp_name, aspsp_country, valid_until
`

type InsertEBankingConnectionParams struct {
	WalletID     int64
	AccessUrl    string
	Name         string
	AspspName    string
	AspspCountry string
	ValidUntil   string
}

func (q *Queries) InsertEBankingConnection(ctx context.Context, arg InsertEBankingConnectionParams) (BankConnection, error) {
	row := q.db.QueryRowContext(ctx, insertEBankingConnection,
		arg.WalletID,
		arg.AccessUrl,
		arg.Name,
		arg.AspspName,
		arg.AspspCountry,
		arg.ValidUntil,
	)
	var i BankConnection
	err := row.Scan(
		&i.ID,
		&i.WalletID,
		&i.Provider,
		&i.AccessUrl,
		&i.Name,
		&i.CreatedAt,
		&i.LastSyncedAt,
		&i.AspspName,
		&i.AspspCountry,
		&i.ValidUntil,
	)
	return i, err
}

const upsertEBankingConfig = `-- name: UpsertEBankingConfig :exec
INSERT INTO bank_ebanking_config (wallet_id, app_id, private_key, environment)
VALUES (?, ?, ?, ?)
ON CONFLICT (wallet_id) DO UPDATE SET
    app_id = excluded.app_id,
    private_key = excluded.private_key,
    environment = excluded.environment,
    updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
`

type UpsertEBankingConfigParams struct {
	WalletID    int64
	AppID       string
	PrivateKey  string
	Environment string
}

func (q *Queries) UpsertEBankingConfig(ctx context.Context, arg UpsertEBankingConfigParams) error {
	_, err := q.db.ExecContext(ctx, upsertEBankingConfig,
		arg.WalletID,
		arg.AppID,
		arg.PrivateKey,
		arg.Environment,
	)
	return err
}
