// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bank_sync.sql

package db

import (
	"context"
	"database/sql"
)

const deleteBankConnection = `-- name: DeleteBankConnection :execrows
DELETE FROM bank_connections WHERE id = ? AND wallet_id = ?
`

type DeleteBankConnectionParams struct {
	ID       int64
	WalletID int64
}

func (q *Queries) DeleteBankConnection(ctx context.Context, arg DeleteBankConnectionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteBankConnection, arg.ID, arg.WalletID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteBankLink = `-- name: DeleteBankLink :exec
DELETE FROM bank_links WHERE connection_id = ? AND external_id = ?
`

type DeleteBankLinkParams struct {
	ConnectionID int64
	ExternalID   string
}

func (q *Queries) DeleteBankLink(ctx context.Context, arg DeleteBankLinkParams) error {
	_, err := q.db.ExecContext(ctx, deleteBankLink, arg.ConnectionID, arg.ExternalID)
	return err
}

const getBankConnection = `-- name: GetBankConnection :one
SELECT id, wallet_id, provider, access_url, name, created_at, last_synced_at, aspsp_name, aspsp_country, valid_until, accounts_json, auto_sync FROM bank_connections WHERE id = ? LIMIT 1
`

func (q *Queries) GetBankConnection(ctx context.Context, id int64) (BankConnection, error) {
	row := q.db.QueryRowContext(ctx, getBankConnection, id)
	var i BankConnection
	err := row.Scan(
		&i.ID,
		&i.WalletID,
		&i.Provider,
		&i.AccessUrl,
		&i.Name,
		&i.CreatedAt,
		&i.LastSyncedAt,
		&i.AspspName,
		&i.AspspCountry,
		&i.ValidUntil,
		&i.AccountsJson,
		&i.AutoSync,
	)
	return i, err
}

const insertBankConnection = `-- name: InsertBankConnection :one
INSERT INTO bank_connections (wallet_id, provider, access_url, name)
VALUES (?, ?, ?, ?)
RETURNING id, wallet_id, provider, access_url, name, created_at, last_synced_at, aspsp_name, aspsp_country, valid_until, accounts_json, auto_sync
`

type InsertBankConnectionParams struct {
	WalletID  int64
	Provider  string
	AccessUrl string
	Name      string
}

func (q *Queries) InsertBankConnection(ctx context.Context, arg InsertBankConnectionParams) (BankConnection, error) {
	row := q.db.QueryRowContext(ctx, insertBankConnection,
		arg.WalletID,
		arg.Provider,
		arg.AccessUrl,
		arg.Name,
	)
	var i BankConnection
	err := row.Scan(
		&i.ID,
		&i.WalletID,
		&i.Provider,
		&i.AccessUrl,
		&i.Name,
		&i.CreatedAt,
		&i.LastSyncedAt,
		&i.AspspName,
		&i.AspspCountry,
		&i.ValidUntil,
		&i.AccountsJson,
		&i.AutoSync,
	)
	return i, err
}

const listBankConnectionsForWallet = `-- name: ListBankConnectionsForWallet :many
SELECT id, wallet_id, provider, access_url, name, created_at, last_synced_at, aspsp_name, aspsp_country, valid_until, accounts_json, auto_sync FROM bank_connections WHERE wallet_id = ? ORDER BY created_at DESC, id
`

func (q *Queries) ListBankConnectionsForWallet(ctx context.Context, walletID int64) ([]BankConnection, error) {
	rows, err := q.db.QueryContext(ctx, listBankConnectionsForWallet, walletID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BankConnection{}
	for rows.Next() {
		var i BankConnection
		if err := rows.Scan(
			&i.ID,
			&i.WalletID,
			&i.Provider,
			&i.AccessUrl,
			&i.Name,
			&i.CreatedAt,
			&i.LastSyncedAt,
			&i.AspspName,
			&i.AspspCountry,
			&i.ValidUntil,
			&i.AccountsJson,
			&i.AutoSync,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBankLinks = `-- name: ListBankLinks :many
SELECT external_id, account_id FROM bank_links WHERE connection_id = ?
`

type ListBankLinksRow struct {
	ExternalID string
	AccountID  int64
}

func (q *Queries) ListBankLinks(ctx context.Context, connectionID int64) ([]ListBankLinksRow, error) {
	rows, err := q.db.QueryContext(ctx, listBankLinks, connectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBankLinksRow{}
	for rows.Next() {
		var i ListBankLinksRow
		if err := rows.Scan(&i.ExternalID, &i.AccountID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDueBankConnections = `-- name: ListDueBankConnections :many
SELECT id, wallet_id FROM bank_connections
WHERE auto_sync = 1 AND (last_synced_at IS NULL OR last_synced_at < ?)
ORDER BY last_synced_at IS NOT NULL, last_synced_at, id
`

type ListDueBankConnectionsRow struct {
	ID       int64
	WalletID int64
}

func (q *Queries) ListDueBankConnections(ctx context.Context, lastSyncedAt sql.NullString) ([]ListDueBankConnectionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listDueBankConnections, lastSyncedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDueBankConnectionsRow{}
	for rows.Next() {
		var i ListDueBankConnectionsRow
		if err := rows.Scan(&i.ID, &i.WalletID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setBankConnectionAutoSync = `-- name: SetBankConnectionAutoSync :execrows
UPDATE bank_connections SET auto_sync = ? WHERE id = ? AND wallet_id = ?
`

type SetBankConnectionAutoSyncParams struct {
	AutoSync int64
	ID       int64
	WalletID int64
}

func (q *Queries) SetBankConnectionAutoSync(ctx context.Context, arg SetBankConnectionAutoSyncParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setBankConnectionAutoSync, arg.AutoSync, arg.ID, arg.WalletID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const touchBankConnection = `-- name: TouchBankConnection :exec
UPDATE bank_connections SET last_synced_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now') WHERE id = ?
`

func (q *Queries) TouchBankConnection(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, touchBankConnection, id)
	return err
}

const upsertBankLink = `-- name: UpsertBankLink :exec
INSERT INTO bank_links (connection_id, external_id, account_id)
VALUES (?, ?, ?)
ON CONFLICT (connection_id, external_id) DO UPDATE SET account_id = excluded.account_id
`

type UpsertBankLinkParams struct {
	ConnectionID int64
	ExternalID   string
	AccountID    int64
}

func (q *Queries) UpsertBankLink(ctx context.Context, arg UpsertBankLinkParams) error {
	_, err := q.db.ExecContext(ctx, upsertBankLink, arg.ConnectionID, arg.ExternalID, arg.AccountID)
	return err
}
