// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bills.sql

package db

import (
	"context"
	"database/sql"
)

const listScheduleBills = `-- name: ListScheduleBills :many
SELECT sch.id, sch.template_id, sch.unit, sch.every_n, sch.next_due,
       sch.weekend_mode, sch.remaining, sch.last_posted, sch.auto_post,
       tpl.name AS template_name, tpl.amount AS template_amount,
       tpl.is_transfer AS template_is_transfer, tpl.account_id AS account_id,
       acc.name AS account_name, acc.currency_id AS currency_id
FROM schedules sch
JOIN templates tpl ON tpl.id = sch.template_id
LEFT JOIN accounts acc ON acc.id = tpl.account_id
WHERE sch.wallet_id = ?
ORDER BY sch.next_due, sch.id
`

type ListScheduleBillsRow struct {
	ID                 int64
	TemplateID         int64
	Unit               string
	EveryN             int64
	NextDue            string
	WeekendMode        int64
	Remaining          sql.NullInt64
	LastPosted         sql.NullString
	AutoPost           int64
	TemplateName       string
	TemplateAmount     int64
	TemplateIsTransfer int64
	AccountID          sql.NullInt64
	AccountName        sql.NullString
	CurrencyID         sql.NullInt64
}

// Every schedule in the wallet with the template fields the Bills view needs:
// amount (signed), the target account and its currency (for base conversion),
// and the recurrence state used to enumerate occurrences and classify them.
func (q *Queries) ListScheduleBills(ctx context.Context, walletID int64) ([]ListScheduleBillsRow, error) {
	rows, err := q.db.QueryContext(ctx, listScheduleBills, walletID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListScheduleBillsRow{}
	for rows.Next() {
		var i ListScheduleBillsRow
		if err := rows.Scan(
			&i.ID,
			&i.TemplateID,
			&i.Unit,
			&i.EveryN,
			&i.NextDue,
			&i.WeekendMode,
			&i.Remaining,
			&i.LastPosted,
			&i.AutoPost,
			&i.TemplateName,
			&i.TemplateAmount,
			&i.TemplateIsTransfer,
			&i.AccountID,
			&i.AccountName,
			&i.CurrencyID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
