// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: budgets.sql

package db

import (
	"context"
	"database/sql"
)

const categoryActualsForBudget = `-- name: CategoryActualsForBudget :many
SELECT t.category_id AS category_id, t.amount AS amount, a.currency_id AS currency_id
FROM transactions t
JOIN accounts a ON a.id = t.account_id
WHERE t.wallet_id = ?1
  AND t.is_split = 0
  AND t.category_id IS NOT NULL
  AND a.no_budget = 0
  AND t.date >= ?2
  AND t.date <= ?3
UNION ALL
SELECT s.category_id AS category_id, s.amount AS amount, a.currency_id AS currency_id
FROM splits s
JOIN transactions t ON t.id = s.transaction_id
JOIN accounts a ON a.id = t.account_id
WHERE t.wallet_id = ?1
  AND s.category_id IS NOT NULL
  AND a.no_budget = 0
  AND t.date >= ?2
  AND t.date <= ?3
`

type CategoryActualsForBudgetParams struct {
	WalletID int64
	FromDate string
	ToDate   string
}

type CategoryActualsForBudgetRow struct {
	CategoryID sql.NullInt64
	Amount     int64
	CurrencyID int64
}

// Category amounts in a date range (plain transactions + split lines), excluding
// accounts flagged no_budget, with each row's currency so the app can convert.
func (q *Queries) CategoryActualsForBudget(ctx context.Context, arg CategoryActualsForBudgetParams) ([]CategoryActualsForBudgetRow, error) {
	rows, err := q.db.QueryContext(ctx, categoryActualsForBudget, arg.WalletID, arg.FromDate, arg.ToDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CategoryActualsForBudgetRow{}
	for rows.Next() {
		var i CategoryActualsForBudgetRow
		if err := rows.Scan(&i.CategoryID, &i.Amount, &i.CurrencyID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteCategoryBudget = `-- name: DeleteCategoryBudget :exec
DELETE FROM budgets WHERE wallet_id = ? AND category_id = ? AND year = ?
`

type DeleteCategoryBudgetParams struct {
	WalletID   int64
	CategoryID int64
	Year       int64
}

func (q *Queries) DeleteCategoryBudget(ctx context.Context, arg DeleteCategoryBudgetParams) error {
	_, err := q.db.ExecContext(ctx, deleteCategoryBudget, arg.WalletID, arg.CategoryID, arg.Year)
	return err
}

const insertBudget = `-- name: InsertBudget :exec
INSERT INTO budgets (wallet_id, category_id, year, month, amount) VALUES (?, ?, ?, ?, ?)
`

type InsertBudgetParams struct {
	WalletID   int64
	CategoryID int64
	Year       int64
	Month      int64
	Amount     int64
}

func (q *Queries) InsertBudget(ctx context.Context, arg InsertBudgetParams) error {
	_, err := q.db.ExecContext(ctx, insertBudget,
		arg.WalletID,
		arg.CategoryID,
		arg.Year,
		arg.Month,
		arg.Amount,
	)
	return err
}

const listBudgetsForWallet = `-- name: ListBudgetsForWallet :many
SELECT id, wallet_id, category_id, year, month, amount FROM budgets WHERE wallet_id = ? ORDER BY category_id, year, month
`

func (q *Queries) ListBudgetsForWallet(ctx context.Context, walletID int64) ([]Budget, error) {
	rows, err := q.db.QueryContext(ctx, listBudgetsForWallet, walletID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Budget{}
	for rows.Next() {
		var i Budget
		if err := rows.Scan(
			&i.ID,
			&i.WalletID,
			&i.CategoryID,
			&i.Year,
			&i.Month,
			&i.Amount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
