// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: categories.sql

package db

import (
	"context"
	"database/sql"
)

const countPayeesWithCategory = `-- name: CountPayeesWithCategory :one
SELECT COUNT(*) FROM payees WHERE default_category_id = ?
`

func (q *Queries) CountPayeesWithCategory(ctx context.Context, defaultCategoryID sql.NullInt64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPayeesWithCategory, defaultCategoryID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSubcategories = `-- name: CountSubcategories :one
SELECT COUNT(*) FROM categories WHERE parent_id = ?
`

func (q *Queries) CountSubcategories(ctx context.Context, parentID sql.NullInt64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSubcategories, parentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteCategory = `-- name: DeleteCategory :exec
DELETE FROM categories WHERE id = ?
`

func (q *Queries) DeleteCategory(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteCategory, id)
	return err
}

const getCategory = `-- name: GetCategory :one
SELECT id, wallet_id, parent_id, name, is_income, no_budget FROM categories WHERE id = ? LIMIT 1
`

func (q *Queries) GetCategory(ctx context.Context, id int64) (Category, error) {
	row := q.db.QueryRowContext(ctx, getCategory, id)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.WalletID,
		&i.ParentID,
		&i.Name,
		&i.IsIncome,
		&i.NoBudget,
	)
	return i, err
}

const insertCategory = `-- name: InsertCategory :one
INSERT INTO categories (wallet_id, parent_id, name, is_income, no_budget)
VALUES (?, ?, ?, ?, ?)
RETURNING id, wallet_id, parent_id, name, is_income, no_budget
`

type InsertCategoryParams struct {
	WalletID int64
	ParentID sql.NullInt64
	Name     string
	IsIncome int64
	NoBudget int64
}

func (q *Queries) InsertCategory(ctx context.Context, arg InsertCategoryParams) (Category, error) {
	row := q.db.QueryRowContext(ctx, insertCategory,
		arg.WalletID,
		arg.ParentID,
		arg.Name,
		arg.IsIncome,
		arg.NoBudget,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.WalletID,
		&i.ParentID,
		&i.Name,
		&i.IsIncome,
		&i.NoBudget,
	)
	return i, err
}

const listCategoriesForWallet = `-- name: ListCategoriesForWallet :many
SELECT id, wallet_id, parent_id, name, is_income, no_budget FROM categories WHERE wallet_id = ? ORDER BY name
`

func (q *Queries) ListCategoriesForWallet(ctx context.Context, walletID int64) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, listCategoriesForWallet, walletID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.WalletID,
			&i.ParentID,
			&i.Name,
			&i.IsIncome,
			&i.NoBudget,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reassignPayeeCategory = `-- name: ReassignPayeeCategory :exec
UPDATE payees SET default_category_id = ? WHERE default_category_id = ?
`

type ReassignPayeeCategoryParams struct {
	DefaultCategoryID   sql.NullInt64
	DefaultCategoryID_2 sql.NullInt64
}

func (q *Queries) ReassignPayeeCategory(ctx context.Context, arg ReassignPayeeCategoryParams) error {
	_, err := q.db.ExecContext(ctx, reassignPayeeCategory, arg.DefaultCategoryID, arg.DefaultCategoryID_2)
	return err
}

const reparentChildren = `-- name: ReparentChildren :exec
UPDATE categories SET parent_id = ? WHERE parent_id = ?
`

type ReparentChildrenParams struct {
	ParentID   sql.NullInt64
	ParentID_2 sql.NullInt64
}

func (q *Queries) ReparentChildren(ctx context.Context, arg ReparentChildrenParams) error {
	_, err := q.db.ExecContext(ctx, reparentChildren, arg.ParentID, arg.ParentID_2)
	return err
}

const setChildrenIncome = `-- name: SetChildrenIncome :exec
UPDATE categories SET is_income = ? WHERE parent_id = ?
`

type SetChildrenIncomeParams struct {
	IsIncome int64
	ParentID sql.NullInt64
}

func (q *Queries) SetChildrenIncome(ctx context.Context, arg SetChildrenIncomeParams) error {
	_, err := q.db.ExecContext(ctx, setChildrenIncome, arg.IsIncome, arg.ParentID)
	return err
}

const updateCategory = `-- name: UpdateCategory :exec
UPDATE categories SET name = ?, is_income = ?, no_budget = ? WHERE id = ?
`

type UpdateCategoryParams struct {
	Name     string
	IsIncome int64
	NoBudget int64
	ID       int64
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) error {
	_, err := q.db.ExecContext(ctx, updateCategory,
		arg.Name,
		arg.IsIncome,
		arg.NoBudget,
		arg.ID,
	)
	return err
}
