// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: categories.sql

package db

import (
	"context"
	"database/sql"
)

const categoryActivity = `-- name: CategoryActivity :many
SELECT t.category_id AS category_id,
       a.currency_id AS currency_id,
       CAST(SUM(CASE WHEN t.date >= ?1 THEN 1 ELSE 0 END) AS INTEGER) AS line_count,
       CAST(SUM(CASE WHEN t.date >= ?1 THEN t.amount ELSE 0 END) AS INTEGER) AS total,
       CAST(MAX(t.date) AS TEXT) AS last_date
FROM transactions t
JOIN accounts a ON a.id = t.account_id
WHERE t.wallet_id = ?2
  AND t.is_split = 0
  AND t.category_id IS NOT NULL
  AND t.date <= ?3
GROUP BY t.category_id, a.currency_id
UNION ALL
SELECT s.category_id AS category_id,
       a.currency_id AS currency_id,
       CAST(SUM(CASE WHEN t.date >= ?1 THEN 1 ELSE 0 END) AS INTEGER) AS line_count,
       CAST(SUM(CASE WHEN t.date >= ?1 THEN s.amount ELSE 0 END) AS INTEGER) AS total,
       CAST(MAX(t.date) AS TEXT) AS last_date
FROM splits s
JOIN transactions t ON t.id = s.transaction_id
JOIN accounts a ON a.id = t.account_id
WHERE t.wallet_id = ?2
  AND s.category_id IS NOT NULL
  AND t.date <= ?3
GROUP BY s.category_id, a.currency_id
`

type CategoryActivityParams struct {
	FromDate string
	WalletID int64
	ToDate   string
}

type CategoryActivityRow struct {
	CategoryID sql.NullInt64
	CurrencyID int64
	LineCount  int64
	Total      int64
	LastDate   string
}

// What each category holds, per account currency: its lines dated in
// [from_date, to_date], their sum, and the latest line on or before to_date.
// Plain transactions and split lines are summed apart, so a category and
// currency can come back twice; the caller adds them up. A split counts once
// per line, under the line's own category. No category is left out, not even
// one hidden from the reports.
func (q *Queries) CategoryActivity(ctx context.Context, arg CategoryActivityParams) ([]CategoryActivityRow, error) {
	rows, err := q.db.QueryContext(ctx, categoryActivity, arg.FromDate, arg.WalletID, arg.ToDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CategoryActivityRow{}
	for rows.Next() {
		var i CategoryActivityRow
		if err := rows.Scan(
			&i.CategoryID,
			&i.CurrencyID,
			&i.LineCount,
			&i.Total,
			&i.LastDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countPayeesWithCategory = `-- name: CountPayeesWithCategory :one
SELECT COUNT(*) FROM payees WHERE default_category_id = ?
`

func (q *Queries) CountPayeesWithCategory(ctx context.Context, defaultCategoryID sql.NullInt64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPayeesWithCategory, defaultCategoryID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSubcategories = `-- name: CountSubcategories :one
SELECT COUNT(*) FROM categories WHERE parent_id = ?
`

func (q *Queries) CountSubcategories(ctx context.Context, parentID sql.NullInt64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSubcategories, parentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTransactionsWithCategory = `-- name: CountTransactionsWithCategory :one
SELECT COUNT(*) FROM transactions WHERE category_id = ?
`

func (q *Queries) CountTransactionsWithCategory(ctx context.Context, categoryID sql.NullInt64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTransactionsWithCategory, categoryID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteCategory = `-- name: DeleteCategory :exec
DELETE FROM categories WHERE id = ?
`

func (q *Queries) DeleteCategory(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteCategory, id)
	return err
}

const getCategory = `-- name: GetCategory :one
SELECT id, wallet_id, parent_id, name, is_income, no_budget, no_report FROM categories WHERE id = ? LIMIT 1
`

func (q *Queries) GetCategory(ctx context.Context, id int64) (Category, error) {
	row := q.db.QueryRowContext(ctx, getCategory, id)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.WalletID,
		&i.ParentID,
		&i.Name,
		&i.IsIncome,
		&i.NoBudget,
		&i.NoReport,
	)
	return i, err
}

const insertCategory = `-- name: InsertCategory :one
INSERT INTO categories (wallet_id, parent_id, name, is_income, no_budget, no_report)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, wallet_id, parent_id, name, is_income, no_budget, no_report
`

type InsertCategoryParams struct {
	WalletID int64
	ParentID sql.NullInt64
	Name     string
	IsIncome int64
	NoBudget int64
	NoReport int64
}

func (q *Queries) InsertCategory(ctx context.Context, arg InsertCategoryParams) (Category, error) {
	row := q.db.QueryRowContext(ctx, insertCategory,
		arg.WalletID,
		arg.ParentID,
		arg.Name,
		arg.IsIncome,
		arg.NoBudget,
		arg.NoReport,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.WalletID,
		&i.ParentID,
		&i.Name,
		&i.IsIncome,
		&i.NoBudget,
		&i.NoReport,
	)
	return i, err
}

const listCategoriesForWallet = `-- name: ListCategoriesForWallet :many
SELECT id, wallet_id, parent_id, name, is_income, no_budget, no_report FROM categories WHERE wallet_id = ? ORDER BY name
`

func (q *Queries) ListCategoriesForWallet(ctx context.Context, walletID int64) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, listCategoriesForWallet, walletID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.WalletID,
			&i.ParentID,
			&i.Name,
			&i.IsIncome,
			&i.NoBudget,
			&i.NoReport,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reassignPayeeCategory = `-- name: ReassignPayeeCategory :exec
UPDATE payees SET default_category_id = ? WHERE default_category_id = ?
`

type ReassignPayeeCategoryParams struct {
	DefaultCategoryID   sql.NullInt64
	DefaultCategoryID_2 sql.NullInt64
}

func (q *Queries) ReassignPayeeCategory(ctx context.Context, arg ReassignPayeeCategoryParams) error {
	_, err := q.db.ExecContext(ctx, reassignPayeeCategory, arg.DefaultCategoryID, arg.DefaultCategoryID_2)
	return err
}

const reassignSplitCategory = `-- name: ReassignSplitCategory :exec
UPDATE splits SET category_id = ? WHERE category_id = ?
`

type ReassignSplitCategoryParams struct {
	CategoryID   sql.NullInt64
	CategoryID_2 sql.NullInt64
}

func (q *Queries) ReassignSplitCategory(ctx context.Context, arg ReassignSplitCategoryParams) error {
	_, err := q.db.ExecContext(ctx, reassignSplitCategory, arg.CategoryID, arg.CategoryID_2)
	return err
}

const reassignTransactionCategory = `-- name: ReassignTransactionCategory :exec
UPDATE transactions SET category_id = ? WHERE category_id = ?
`

type ReassignTransactionCategoryParams struct {
	CategoryID   sql.NullInt64
	CategoryID_2 sql.NullInt64
}

func (q *Queries) ReassignTransactionCategory(ctx context.Context, arg ReassignTransactionCategoryParams) error {
	_, err := q.db.ExecContext(ctx, reassignTransactionCategory, arg.CategoryID, arg.CategoryID_2)
	return err
}

const reparentChildren = `-- name: ReparentChildren :exec
UPDATE categories SET parent_id = ? WHERE parent_id = ?
`

type ReparentChildrenParams struct {
	ParentID   sql.NullInt64
	ParentID_2 sql.NullInt64
}

func (q *Queries) ReparentChildren(ctx context.Context, arg ReparentChildrenParams) error {
	_, err := q.db.ExecContext(ctx, reparentChildren, arg.ParentID, arg.ParentID_2)
	return err
}

const setChildrenIncome = `-- name: SetChildrenIncome :exec
UPDATE categories SET is_income = ? WHERE parent_id = ?
`

type SetChildrenIncomeParams struct {
	IsIncome int64
	ParentID sql.NullInt64
}

func (q *Queries) SetChildrenIncome(ctx context.Context, arg SetChildrenIncomeParams) error {
	_, err := q.db.ExecContext(ctx, setChildrenIncome, arg.IsIncome, arg.ParentID)
	return err
}

const updateCategory = `-- name: UpdateCategory :exec
UPDATE categories SET parent_id = ?, name = ?, is_income = ?, no_budget = ?, no_report = ? WHERE id = ?
`

type UpdateCategoryParams struct {
	ParentID sql.NullInt64
	Name     string
	IsIncome int64
	NoBudget int64
	NoReport int64
	ID       int64
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) error {
	_, err := q.db.ExecContext(ctx, updateCategory,
		arg.ParentID,
		arg.Name,
		arg.IsIncome,
		arg.NoBudget,
		arg.NoReport,
		arg.ID,
	)
	return err
}
