// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: currencies.sql

package db

import (
	"context"
	"database/sql"
)

const clearWalletBase = `-- name: ClearWalletBase :exec
UPDATE currencies SET is_base = 0 WHERE wallet_id = ?
`

func (q *Queries) ClearWalletBase(ctx context.Context, walletID int64) error {
	_, err := q.db.ExecContext(ctx, clearWalletBase, walletID)
	return err
}

const countWalletCurrencies = `-- name: CountWalletCurrencies :one
SELECT COUNT(*) FROM currencies WHERE wallet_id = ?
`

func (q *Queries) CountWalletCurrencies(ctx context.Context, walletID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countWalletCurrencies, walletID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteCurrency = `-- name: DeleteCurrency :exec
DELETE FROM currencies WHERE id = ?
`

func (q *Queries) DeleteCurrency(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteCurrency, id)
	return err
}

const getBaseCurrency = `-- name: GetBaseCurrency :one
SELECT id, wallet_id, iso_code, name, symbol, symbol_prefix, decimal_char, group_char, frac_digits, is_base, rate, rate_updated_at FROM currencies WHERE wallet_id = ? AND is_base = 1 LIMIT 1
`

func (q *Queries) GetBaseCurrency(ctx context.Context, walletID int64) (Currency, error) {
	row := q.db.QueryRowContext(ctx, getBaseCurrency, walletID)
	var i Currency
	err := row.Scan(
		&i.ID,
		&i.WalletID,
		&i.IsoCode,
		&i.Name,
		&i.Symbol,
		&i.SymbolPrefix,
		&i.DecimalChar,
		&i.GroupChar,
		&i.FracDigits,
		&i.IsBase,
		&i.Rate,
		&i.RateUpdatedAt,
	)
	return i, err
}

const getCurrency = `-- name: GetCurrency :one
SELECT id, wallet_id, iso_code, name, symbol, symbol_prefix, decimal_char, group_char, frac_digits, is_base, rate, rate_updated_at FROM currencies WHERE id = ? LIMIT 1
`

func (q *Queries) GetCurrency(ctx context.Context, id int64) (Currency, error) {
	row := q.db.QueryRowContext(ctx, getCurrency, id)
	var i Currency
	err := row.Scan(
		&i.ID,
		&i.WalletID,
		&i.IsoCode,
		&i.Name,
		&i.Symbol,
		&i.SymbolPrefix,
		&i.DecimalChar,
		&i.GroupChar,
		&i.FracDigits,
		&i.IsBase,
		&i.Rate,
		&i.RateUpdatedAt,
	)
	return i, err
}

const insertCurrency = `-- name: InsertCurrency :one
INSERT INTO currencies (
    wallet_id, iso_code, name, symbol, symbol_prefix,
    decimal_char, group_char, frac_digits, is_base, rate
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, wallet_id, iso_code, name, symbol, symbol_prefix, decimal_char, group_char, frac_digits, is_base, rate, rate_updated_at
`

type InsertCurrencyParams struct {
	WalletID     int64
	IsoCode      string
	Name         string
	Symbol       string
	SymbolPrefix int64
	DecimalChar  string
	GroupChar    string
	FracDigits   int64
	IsBase       int64
	Rate         float64
}

func (q *Queries) InsertCurrency(ctx context.Context, arg InsertCurrencyParams) (Currency, error) {
	row := q.db.QueryRowContext(ctx, insertCurrency,
		arg.WalletID,
		arg.IsoCode,
		arg.Name,
		arg.Symbol,
		arg.SymbolPrefix,
		arg.DecimalChar,
		arg.GroupChar,
		arg.FracDigits,
		arg.IsBase,
		arg.Rate,
	)
	var i Currency
	err := row.Scan(
		&i.ID,
		&i.WalletID,
		&i.IsoCode,
		&i.Name,
		&i.Symbol,
		&i.SymbolPrefix,
		&i.DecimalChar,
		&i.GroupChar,
		&i.FracDigits,
		&i.IsBase,
		&i.Rate,
		&i.RateUpdatedAt,
	)
	return i, err
}

const listCurrenciesForWallet = `-- name: ListCurrenciesForWallet :many
SELECT id, wallet_id, iso_code, name, symbol, symbol_prefix, decimal_char, group_char, frac_digits, is_base, rate, rate_updated_at FROM currencies WHERE wallet_id = ? ORDER BY is_base DESC, iso_code
`

func (q *Queries) ListCurrenciesForWallet(ctx context.Context, walletID int64) ([]Currency, error) {
	rows, err := q.db.QueryContext(ctx, listCurrenciesForWallet, walletID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Currency{}
	for rows.Next() {
		var i Currency
		if err := rows.Scan(
			&i.ID,
			&i.WalletID,
			&i.IsoCode,
			&i.Name,
			&i.Symbol,
			&i.SymbolPrefix,
			&i.DecimalChar,
			&i.GroupChar,
			&i.FracDigits,
			&i.IsBase,
			&i.Rate,
			&i.RateUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExchangeRates = `-- name: ListExchangeRates :many
SELECT id, currency_id, date, rate, source FROM exchange_rates WHERE currency_id = ? ORDER BY date DESC
`

func (q *Queries) ListExchangeRates(ctx context.Context, currencyID int64) ([]ExchangeRate, error) {
	rows, err := q.db.QueryContext(ctx, listExchangeRates, currencyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExchangeRate{}
	for rows.Next() {
		var i ExchangeRate
		if err := rows.Scan(
			&i.ID,
			&i.CurrencyID,
			&i.Date,
			&i.Rate,
			&i.Source,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setCurrencyBase = `-- name: SetCurrencyBase :exec
UPDATE currencies SET is_base = 1, rate = 1 WHERE id = ?
`

func (q *Queries) SetCurrencyBase(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, setCurrencyBase, id)
	return err
}

const updateCurrencyFormat = `-- name: UpdateCurrencyFormat :exec
UPDATE currencies
SET symbol = ?, symbol_prefix = ?, decimal_char = ?, group_char = ?, frac_digits = ?
WHERE id = ?
`

type UpdateCurrencyFormatParams struct {
	Symbol       string
	SymbolPrefix int64
	DecimalChar  string
	GroupChar    string
	FracDigits   int64
	ID           int64
}

func (q *Queries) UpdateCurrencyFormat(ctx context.Context, arg UpdateCurrencyFormatParams) error {
	_, err := q.db.ExecContext(ctx, updateCurrencyFormat,
		arg.Symbol,
		arg.SymbolPrefix,
		arg.DecimalChar,
		arg.GroupChar,
		arg.FracDigits,
		arg.ID,
	)
	return err
}

const updateCurrencyRate = `-- name: UpdateCurrencyRate :exec
UPDATE currencies
SET rate = ?, rate_updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ?
`

type UpdateCurrencyRateParams struct {
	Rate float64
	ID   int64
}

func (q *Queries) UpdateCurrencyRate(ctx context.Context, arg UpdateCurrencyRateParams) error {
	_, err := q.db.ExecContext(ctx, updateCurrencyRate, arg.Rate, arg.ID)
	return err
}

const updateWalletBaseCurrency = `-- name: UpdateWalletBaseCurrency :exec
UPDATE wallets SET base_currency_id = ? WHERE id = ?
`

type UpdateWalletBaseCurrencyParams struct {
	BaseCurrencyID sql.NullInt64
	ID             int64
}

func (q *Queries) UpdateWalletBaseCurrency(ctx context.Context, arg UpdateWalletBaseCurrencyParams) error {
	_, err := q.db.ExecContext(ctx, updateWalletBaseCurrency, arg.BaseCurrencyID, arg.ID)
	return err
}

const upsertExchangeRate = `-- name: UpsertExchangeRate :exec
INSERT INTO exchange_rates (currency_id, date, rate, source)
VALUES (?, ?, ?, ?)
ON CONFLICT (currency_id, date) DO UPDATE SET rate = excluded.rate, source = excluded.source
`

type UpsertExchangeRateParams struct {
	CurrencyID int64
	Date       string
	Rate       float64
	Source     string
}

func (q *Queries) UpsertExchangeRate(ctx context.Context, arg UpsertExchangeRateParams) error {
	_, err := q.db.ExecContext(ctx, upsertExchangeRate,
		arg.CurrencyID,
		arg.Date,
		arg.Rate,
		arg.Source,
	)
	return err
}
