// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dashboard.sql

package db

import (
	"context"
	"database/sql"
)

const accountBalanceDeltas = `-- name: AccountBalanceDeltas :many
SELECT
    account_id,
    CAST(SUM(amount) AS INTEGER) AS future_delta,
    CAST(SUM(CASE WHEN date <= ?1 THEN amount ELSE 0 END) AS INTEGER) AS today_delta,
    CAST(SUM(CASE WHEN status IN (1, 2) THEN amount ELSE 0 END) AS INTEGER) AS bank_delta
FROM transactions
WHERE wallet_id = ?2
GROUP BY account_id
`

type AccountBalanceDeltasParams struct {
	Today    string
	WalletID int64
}

type AccountBalanceDeltasRow struct {
	AccountID   int64
	FutureDelta int64
	TodayDelta  int64
	BankDelta   int64
}

// Per-account transaction sums using the same definitions as the register
// header: future = all, today = dated on/before today, bank = cleared(1) or
// reconciled(2). The application adds each account's initial balance.
func (q *Queries) AccountBalanceDeltas(ctx context.Context, arg AccountBalanceDeltasParams) ([]AccountBalanceDeltasRow, error) {
	rows, err := q.db.QueryContext(ctx, accountBalanceDeltas, arg.Today, arg.WalletID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AccountBalanceDeltasRow{}
	for rows.Next() {
		var i AccountBalanceDeltasRow
		if err := rows.Scan(
			&i.AccountID,
			&i.FutureDelta,
			&i.TodayDelta,
			&i.BankDelta,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const categoryExpenseTotals = `-- name: CategoryExpenseTotals :many
SELECT t.category_id AS category_id, t.amount AS amount, a.currency_id AS currency_id
FROM transactions t
JOIN accounts a ON a.id = t.account_id
WHERE t.wallet_id = ?1
  AND t.is_split = 0
  AND t.category_id IS NOT NULL
  AND t.date >= ?2
  AND t.date <= ?3
UNION ALL
SELECT s.category_id AS category_id, s.amount AS amount, a.currency_id AS currency_id
FROM splits s
JOIN transactions t ON t.id = s.transaction_id
JOIN accounts a ON a.id = t.account_id
WHERE t.wallet_id = ?1
  AND s.category_id IS NOT NULL
  AND t.date >= ?2
  AND t.date <= ?3
`

type CategoryExpenseTotalsParams struct {
	WalletID int64
	FromDate string
	ToDate   string
}

type CategoryExpenseTotalsRow struct {
	CategoryID sql.NullInt64
	Amount     int64
	CurrencyID int64
}

// Category amounts in a date range, from both plain transactions and split
// lines, with each row's account currency so the app can convert to base.
func (q *Queries) CategoryExpenseTotals(ctx context.Context, arg CategoryExpenseTotalsParams) ([]CategoryExpenseTotalsRow, error) {
	rows, err := q.db.QueryContext(ctx, categoryExpenseTotals, arg.WalletID, arg.FromDate, arg.ToDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CategoryExpenseTotalsRow{}
	for rows.Next() {
		var i CategoryExpenseTotalsRow
		if err := rows.Scan(&i.CategoryID, &i.Amount, &i.CurrencyID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const payeeExpenseTotals = `-- name: PayeeExpenseTotals :many
SELECT t.payee_id AS payee_id, t.amount AS amount, a.currency_id AS currency_id
FROM transactions t
JOIN accounts a ON a.id = t.account_id
WHERE t.wallet_id = ?1
  AND t.payee_id IS NOT NULL
  AND t.date >= ?2
  AND t.date <= ?3
`

type PayeeExpenseTotalsParams struct {
	WalletID int64
	FromDate string
	ToDate   string
}

type PayeeExpenseTotalsRow struct {
	PayeeID    sql.NullInt64
	Amount     int64
	CurrencyID int64
}

// Payee amounts in a date range. Payee is a per-transaction attribute, so split
// transactions contribute via their parent's total amount; each row carries the
// account currency so the app can convert to base.
func (q *Queries) PayeeExpenseTotals(ctx context.Context, arg PayeeExpenseTotalsParams) ([]PayeeExpenseTotalsRow, error) {
	rows, err := q.db.QueryContext(ctx, payeeExpenseTotals, arg.WalletID, arg.FromDate, arg.ToDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PayeeExpenseTotalsRow{}
	for rows.Next() {
		var i PayeeExpenseTotalsRow
		if err := rows.Scan(&i.PayeeID, &i.Amount, &i.CurrencyID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
