// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: demo.sql

package db

import (
	"context"
)

const demoCountUserWallets = `-- name: DemoCountUserWallets :one
SELECT COUNT(*) FROM wallet_members WHERE user_id = ?
`

func (q *Queries) DemoCountUserWallets(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, demoCountUserWallets, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const demoCountWalletTransactions = `-- name: DemoCountWalletTransactions :one
SELECT COUNT(*) FROM transactions WHERE wallet_id = ?
`

func (q *Queries) DemoCountWalletTransactions(ctx context.Context, walletID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, demoCountWalletTransactions, walletID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const demoDeleteIdleUsers = `-- name: DemoDeleteIdleUsers :execrows
DELETE FROM users WHERE NOT EXISTS (
    SELECT 1 FROM sessions s WHERE s.user_id = users.id AND s.expires_at > ?
)
`

func (q *Queries) DemoDeleteIdleUsers(ctx context.Context, expiresAt string) (int64, error) {
	result, err := q.db.ExecContext(ctx, demoDeleteIdleUsers, expiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const demoDeleteWalletsOfIdleUsers = `-- name: DemoDeleteWalletsOfIdleUsers :exec

DELETE FROM wallets WHERE id IN (
    SELECT m.wallet_id FROM wallet_members m
    WHERE NOT EXISTS (
        SELECT 1 FROM sessions s WHERE s.user_id = m.user_id AND s.expires_at > ?
    )
)
`

// Queries for the public demo build only (the `demo` build tag). A demo runs on
// a disposable database whose every user is a throwaway, so these delete
// freely; nothing outside internal/demo may call them.
// A demo user is idle once no session of theirs outlives the cutoff. Their
// wallets go first: wallets are not tied to users by a cascade.
func (q *Queries) DemoDeleteWalletsOfIdleUsers(ctx context.Context, expiresAt string) error {
	_, err := q.db.ExecContext(ctx, demoDeleteWalletsOfIdleUsers, expiresAt)
	return err
}
