// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: goals.sql

package db

import (
	"context"
	"database/sql"
)

const deleteContribution = `-- name: DeleteContribution :exec
DELETE FROM goal_contributions WHERE id = ?
`

func (q *Queries) DeleteContribution(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteContribution, id)
	return err
}

const deleteGoal = `-- name: DeleteGoal :exec
DELETE FROM goals WHERE id = ?
`

func (q *Queries) DeleteGoal(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteGoal, id)
	return err
}

const getContribution = `-- name: GetContribution :one
SELECT id, goal_id, date, amount, note FROM goal_contributions WHERE id = ? LIMIT 1
`

func (q *Queries) GetContribution(ctx context.Context, id int64) (GoalContribution, error) {
	row := q.db.QueryRowContext(ctx, getContribution, id)
	var i GoalContribution
	err := row.Scan(
		&i.ID,
		&i.GoalID,
		&i.Date,
		&i.Amount,
		&i.Note,
	)
	return i, err
}

const getGoal = `-- name: GetGoal :one
SELECT id, wallet_id, name, target_amount, target_date, account_id, note, position FROM goals WHERE id = ? LIMIT 1
`

func (q *Queries) GetGoal(ctx context.Context, id int64) (Goal, error) {
	row := q.db.QueryRowContext(ctx, getGoal, id)
	var i Goal
	err := row.Scan(
		&i.ID,
		&i.WalletID,
		&i.Name,
		&i.TargetAmount,
		&i.TargetDate,
		&i.AccountID,
		&i.Note,
		&i.Position,
	)
	return i, err
}

const goalSaved = `-- name: GoalSaved :one
SELECT CAST(COALESCE(SUM(amount), 0) AS INTEGER) FROM goal_contributions WHERE goal_id = ?
`

func (q *Queries) GoalSaved(ctx context.Context, goalID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, goalSaved, goalID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const insertContribution = `-- name: InsertContribution :one
INSERT INTO goal_contributions (goal_id, date, amount, note)
VALUES (?, ?, ?, ?)
RETURNING id, goal_id, date, amount, note
`

type InsertContributionParams struct {
	GoalID int64
	Date   string
	Amount int64
	Note   string
}

func (q *Queries) InsertContribution(ctx context.Context, arg InsertContributionParams) (GoalContribution, error) {
	row := q.db.QueryRowContext(ctx, insertContribution,
		arg.GoalID,
		arg.Date,
		arg.Amount,
		arg.Note,
	)
	var i GoalContribution
	err := row.Scan(
		&i.ID,
		&i.GoalID,
		&i.Date,
		&i.Amount,
		&i.Note,
	)
	return i, err
}

const insertGoal = `-- name: InsertGoal :one
INSERT INTO goals (wallet_id, name, target_amount, target_date, account_id, note, position)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, wallet_id, name, target_amount, target_date, account_id, note, position
`

type InsertGoalParams struct {
	WalletID     int64
	Name         string
	TargetAmount int64
	TargetDate   sql.NullString
	AccountID    sql.NullInt64
	Note         string
	Position     int64
}

func (q *Queries) InsertGoal(ctx context.Context, arg InsertGoalParams) (Goal, error) {
	row := q.db.QueryRowContext(ctx, insertGoal,
		arg.WalletID,
		arg.Name,
		arg.TargetAmount,
		arg.TargetDate,
		arg.AccountID,
		arg.Note,
		arg.Position,
	)
	var i Goal
	err := row.Scan(
		&i.ID,
		&i.WalletID,
		&i.Name,
		&i.TargetAmount,
		&i.TargetDate,
		&i.AccountID,
		&i.Note,
		&i.Position,
	)
	return i, err
}

const listContributionsForGoal = `-- name: ListContributionsForGoal :many
SELECT id, goal_id, date, amount, note FROM goal_contributions WHERE goal_id = ? ORDER BY date DESC, id DESC
`

func (q *Queries) ListContributionsForGoal(ctx context.Context, goalID int64) ([]GoalContribution, error) {
	rows, err := q.db.QueryContext(ctx, listContributionsForGoal, goalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GoalContribution{}
	for rows.Next() {
		var i GoalContribution
		if err := rows.Scan(
			&i.ID,
			&i.GoalID,
			&i.Date,
			&i.Amount,
			&i.Note,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGoalsForWallet = `-- name: ListGoalsForWallet :many
SELECT
    g.id, g.wallet_id, g.name, g.target_amount, g.target_date, g.account_id, g.note, g.position,
    CAST(COALESCE((SELECT SUM(amount) FROM goal_contributions c WHERE c.goal_id = g.id), 0) AS INTEGER) AS saved
FROM goals g
WHERE g.wallet_id = ?
ORDER BY g.position, g.name
`

type ListGoalsForWalletRow struct {
	ID           int64
	WalletID     int64
	Name         string
	TargetAmount int64
	TargetDate   sql.NullString
	AccountID    sql.NullInt64
	Note         string
	Position     int64
	Saved        int64
}

func (q *Queries) ListGoalsForWallet(ctx context.Context, walletID int64) ([]ListGoalsForWalletRow, error) {
	rows, err := q.db.QueryContext(ctx, listGoalsForWallet, walletID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGoalsForWalletRow{}
	for rows.Next() {
		var i ListGoalsForWalletRow
		if err := rows.Scan(
			&i.ID,
			&i.WalletID,
			&i.Name,
			&i.TargetAmount,
			&i.TargetDate,
			&i.AccountID,
			&i.Note,
			&i.Position,
			&i.Saved,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGoal = `-- name: UpdateGoal :exec
UPDATE goals
SET name = ?, target_amount = ?, target_date = ?, account_id = ?, note = ?, position = ?
WHERE id = ?
`

type UpdateGoalParams struct {
	Name         string
	TargetAmount int64
	TargetDate   sql.NullString
	AccountID    sql.NullInt64
	Note         string
	Position     int64
	ID           int64
}

func (q *Queries) UpdateGoal(ctx context.Context, arg UpdateGoalParams) error {
	_, err := q.db.ExecContext(ctx, updateGoal,
		arg.Name,
		arg.TargetAmount,
		arg.TargetDate,
		arg.AccountID,
		arg.Note,
		arg.Position,
		arg.ID,
	)
	return err
}
