// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: instance.sql

package db

import (
	"context"
)

const getInstanceSetting = `-- name: GetInstanceSetting :one
SELECT value FROM instance_settings WHERE key = ?
`

func (q *Queries) GetInstanceSetting(ctx context.Context, key string) (string, error) {
	row := q.db.QueryRowContext(ctx, getInstanceSetting, key)
	var value string
	err := row.Scan(&value)
	return value, err
}

const setInstanceSetting = `-- name: SetInstanceSetting :exec
INSERT INTO instance_settings (key, value) VALUES (?, ?)
ON CONFLICT (key) DO UPDATE SET value = excluded.value
`

type SetInstanceSettingParams struct {
	Key   string
	Value string
}

func (q *Queries) SetInstanceSetting(ctx context.Context, arg SetInstanceSettingParams) error {
	_, err := q.db.ExecContext(ctx, setInstanceSetting, arg.Key, arg.Value)
	return err
}
