// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
)

type Account struct {
	ID             int64
	WalletID       int64
	Name           string
	Type           string
	CurrencyID     int64
	Institution    string
	Number         string
	InitialBalance int64
	MinimumBalance int64
	Closed         int64
	NoSummary      int64
	NoBudget       int64
	NoReport       int64
	Position       int64
	GroupName      string
	Notes          string
	Website        string
	CreatedAt      string
}

type Category struct {
	ID       int64
	WalletID int64
	ParentID sql.NullInt64
	Name     string
	IsIncome int64
	NoBudget int64
}

type Currency struct {
	ID            int64
	WalletID      int64
	IsoCode       string
	Name          string
	Symbol        string
	SymbolPrefix  int64
	DecimalChar   string
	GroupChar     string
	FracDigits    int64
	IsBase        int64
	Rate          float64
	RateUpdatedAt sql.NullString
}

type ExchangeRate struct {
	ID         int64
	CurrencyID int64
	Date       string
	Rate       float64
	Source     string
}

type Payee struct {
	ID                 int64
	WalletID           int64
	Name               string
	DefaultCategoryID  sql.NullInt64
	DefaultPaymentMode sql.NullInt64
}

type Schedule struct {
	ID          int64
	WalletID    int64
	TemplateID  int64
	Unit        string
	EveryN      int64
	NextDue     string
	WeekendMode int64
	Remaining   sql.NullInt64
	PostAdvance int64
	AutoPost    int64
	LastPosted  sql.NullString
	CreatedAt   string
}

type Session struct {
	ID         string
	UserID     int64
	CreatedAt  string
	ExpiresAt  string
	LastSeenAt string
	UserAgent  string
}

type Split struct {
	ID            int64
	TransactionID int64
	CategoryID    sql.NullInt64
	Amount        int64
	Memo          string
	Position      int64
}

type Tag struct {
	ID       int64
	WalletID int64
	Name     string
}

type Template struct {
	ID          int64
	WalletID    int64
	Name        string
	AccountID   sql.NullInt64
	Amount      int64
	PaymentMode int64
	Status      int64
	Info        string
	PayeeID     sql.NullInt64
	CategoryID  sql.NullInt64
	Memo        string
	Tags        string
	IsSplit     int64
	IsTransfer  int64
	ToAccountID sql.NullInt64
	CreatedAt   string
}

type TemplateSplit struct {
	ID         int64
	TemplateID int64
	CategoryID sql.NullInt64
	Amount     int64
	Memo       string
	Position   int64
}

type Transaction struct {
	ID          int64
	WalletID    int64
	AccountID   int64
	Date        string
	Amount      int64
	PaymentMode int64
	Status      int64
	Info        string
	PayeeID     sql.NullInt64
	CategoryID  sql.NullInt64
	Memo        string
	IsSplit     int64
	CreatedAt   string
	UpdatedAt   string
	TemplateID  sql.NullInt64
}

type TransactionTag struct {
	TransactionID int64
	TagID         int64
}

type Transfer struct {
	ID        int64
	TxnFromID int64
	TxnToID   int64
}

type User struct {
	ID           int64
	Username     string
	Email        string
	PasswordHash string
	IsAdmin      int64
	Locale       string
	Theme        string
	Disabled     int64
	CreatedAt    string
}

type Wallet struct {
	ID             int64
	Title          string
	OwnerName      string
	BaseCurrencyID sql.NullInt64
	SettingsJson   string
	CreatedAt      string
}

type WalletMember struct {
	WalletID int64
	UserID   int64
	Role     string
}
