// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
)

type Currency struct {
	ID            int64
	WalletID      int64
	IsoCode       string
	Name          string
	Symbol        string
	SymbolPrefix  int64
	DecimalChar   string
	GroupChar     string
	FracDigits    int64
	IsBase        int64
	Rate          float64
	RateUpdatedAt sql.NullString
}

type ExchangeRate struct {
	ID         int64
	CurrencyID int64
	Date       string
	Rate       float64
	Source     string
}

type Session struct {
	ID         string
	UserID     int64
	CreatedAt  string
	ExpiresAt  string
	LastSeenAt string
	UserAgent  string
}

type User struct {
	ID           int64
	Username     string
	Email        string
	PasswordHash string
	IsAdmin      int64
	Locale       string
	Theme        string
	Disabled     int64
	CreatedAt    string
}

type Wallet struct {
	ID             int64
	Title          string
	OwnerName      string
	BaseCurrencyID sql.NullInt64
	SettingsJson   string
	CreatedAt      string
}

type WalletMember struct {
	WalletID int64
	UserID   int64
	Role     string
}
