// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: oidc.sql

package db

import (
	"context"
)

const getUserIDByOIDCIdentity = `-- name: GetUserIDByOIDCIdentity :one
SELECT user_id FROM user_oidc_identities WHERE issuer = ? AND subject = ? LIMIT 1
`

type GetUserIDByOIDCIdentityParams struct {
	Issuer  string
	Subject string
}

func (q *Queries) GetUserIDByOIDCIdentity(ctx context.Context, arg GetUserIDByOIDCIdentityParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getUserIDByOIDCIdentity, arg.Issuer, arg.Subject)
	var user_id int64
	err := row.Scan(&user_id)
	return user_id, err
}

const linkOIDCIdentity = `-- name: LinkOIDCIdentity :exec
INSERT INTO user_oidc_identities (user_id, issuer, subject)
VALUES (?, ?, ?)
ON CONFLICT (issuer, subject) DO NOTHING
`

type LinkOIDCIdentityParams struct {
	UserID  int64
	Issuer  string
	Subject string
}

func (q *Queries) LinkOIDCIdentity(ctx context.Context, arg LinkOIDCIdentityParams) error {
	_, err := q.db.ExecContext(ctx, linkOIDCIdentity, arg.UserID, arg.Issuer, arg.Subject)
	return err
}
