// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payees.sql

package db

import (
	"context"
	"database/sql"
)

const deletePayee = `-- name: DeletePayee :exec
DELETE FROM payees WHERE id = ?
`

func (q *Queries) DeletePayee(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deletePayee, id)
	return err
}

const getPayee = `-- name: GetPayee :one
SELECT id, wallet_id, name, default_category_id, default_payment_mode FROM payees WHERE id = ? LIMIT 1
`

func (q *Queries) GetPayee(ctx context.Context, id int64) (Payee, error) {
	row := q.db.QueryRowContext(ctx, getPayee, id)
	var i Payee
	err := row.Scan(
		&i.ID,
		&i.WalletID,
		&i.Name,
		&i.DefaultCategoryID,
		&i.DefaultPaymentMode,
	)
	return i, err
}

const insertPayee = `-- name: InsertPayee :one
INSERT INTO payees (wallet_id, name, default_category_id, default_payment_mode)
VALUES (?, ?, ?, ?)
RETURNING id, wallet_id, name, default_category_id, default_payment_mode
`

type InsertPayeeParams struct {
	WalletID           int64
	Name               string
	DefaultCategoryID  sql.NullInt64
	DefaultPaymentMode sql.NullInt64
}

func (q *Queries) InsertPayee(ctx context.Context, arg InsertPayeeParams) (Payee, error) {
	row := q.db.QueryRowContext(ctx, insertPayee,
		arg.WalletID,
		arg.Name,
		arg.DefaultCategoryID,
		arg.DefaultPaymentMode,
	)
	var i Payee
	err := row.Scan(
		&i.ID,
		&i.WalletID,
		&i.Name,
		&i.DefaultCategoryID,
		&i.DefaultPaymentMode,
	)
	return i, err
}

const listPayeesForWallet = `-- name: ListPayeesForWallet :many
SELECT id, wallet_id, name, default_category_id, default_payment_mode FROM payees WHERE wallet_id = ? ORDER BY name
`

func (q *Queries) ListPayeesForWallet(ctx context.Context, walletID int64) ([]Payee, error) {
	rows, err := q.db.QueryContext(ctx, listPayeesForWallet, walletID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Payee{}
	for rows.Next() {
		var i Payee
		if err := rows.Scan(
			&i.ID,
			&i.WalletID,
			&i.Name,
			&i.DefaultCategoryID,
			&i.DefaultPaymentMode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePayee = `-- name: UpdatePayee :exec
UPDATE payees SET name = ?, default_category_id = ?, default_payment_mode = ? WHERE id = ?
`

type UpdatePayeeParams struct {
	Name               string
	DefaultCategoryID  sql.NullInt64
	DefaultPaymentMode sql.NullInt64
	ID                 int64
}

func (q *Queries) UpdatePayee(ctx context.Context, arg UpdatePayeeParams) error {
	_, err := q.db.ExecContext(ctx, updatePayee,
		arg.Name,
		arg.DefaultCategoryID,
		arg.DefaultPaymentMode,
		arg.ID,
	)
	return err
}
