// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: push.sql

package db

import (
	"context"
)

const deletePushSubscription = `-- name: DeletePushSubscription :exec
DELETE FROM push_subscriptions WHERE user_id = ? AND endpoint = ?
`

type DeletePushSubscriptionParams struct {
	UserID   int64
	Endpoint string
}

func (q *Queries) DeletePushSubscription(ctx context.Context, arg DeletePushSubscriptionParams) error {
	_, err := q.db.ExecContext(ctx, deletePushSubscription, arg.UserID, arg.Endpoint)
	return err
}

const deletePushSubscriptionByEndpoint = `-- name: DeletePushSubscriptionByEndpoint :exec
DELETE FROM push_subscriptions WHERE endpoint = ?
`

func (q *Queries) DeletePushSubscriptionByEndpoint(ctx context.Context, endpoint string) error {
	_, err := q.db.ExecContext(ctx, deletePushSubscriptionByEndpoint, endpoint)
	return err
}

const getAppConfig = `-- name: GetAppConfig :one
SELECT value FROM app_config WHERE key = ?
`

func (q *Queries) GetAppConfig(ctx context.Context, key string) (string, error) {
	row := q.db.QueryRowContext(ctx, getAppConfig, key)
	var value string
	err := row.Scan(&value)
	return value, err
}

const insertReminderIfNew = `-- name: InsertReminderIfNew :execrows
INSERT OR IGNORE INTO push_reminders (user_id, ref) VALUES (?, ?)
`

type InsertReminderIfNewParams struct {
	UserID int64
	Ref    string
}

func (q *Queries) InsertReminderIfNew(ctx context.Context, arg InsertReminderIfNewParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertReminderIfNew, arg.UserID, arg.Ref)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listPushSubscriptionsForUser = `-- name: ListPushSubscriptionsForUser :many
SELECT endpoint, p256dh, auth FROM push_subscriptions WHERE user_id = ?
`

type ListPushSubscriptionsForUserRow struct {
	Endpoint string
	P256dh   string
	Auth     string
}

func (q *Queries) ListPushSubscriptionsForUser(ctx context.Context, userID int64) ([]ListPushSubscriptionsForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listPushSubscriptionsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPushSubscriptionsForUserRow{}
	for rows.Next() {
		var i ListPushSubscriptionsForUserRow
		if err := rows.Scan(&i.Endpoint, &i.P256dh, &i.Auth); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPushUserIDs = `-- name: ListPushUserIDs :many
SELECT DISTINCT user_id FROM push_subscriptions
`

func (q *Queries) ListPushUserIDs(ctx context.Context) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listPushUserIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var user_id int64
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setAppConfig = `-- name: SetAppConfig :exec
INSERT INTO app_config (key, value) VALUES (?, ?)
ON CONFLICT (key) DO UPDATE SET value = excluded.value
`

type SetAppConfigParams struct {
	Key   string
	Value string
}

func (q *Queries) SetAppConfig(ctx context.Context, arg SetAppConfigParams) error {
	_, err := q.db.ExecContext(ctx, setAppConfig, arg.Key, arg.Value)
	return err
}

const upsertPushSubscription = `-- name: UpsertPushSubscription :exec
INSERT INTO push_subscriptions (user_id, endpoint, p256dh, auth)
VALUES (?, ?, ?, ?)
ON CONFLICT (endpoint) DO UPDATE SET
    user_id = excluded.user_id, p256dh = excluded.p256dh, auth = excluded.auth
`

type UpsertPushSubscriptionParams struct {
	UserID   int64
	Endpoint string
	P256dh   string
	Auth     string
}

func (q *Queries) UpsertPushSubscription(ctx context.Context, arg UpsertPushSubscriptionParams) error {
	_, err := q.db.ExecContext(ctx, upsertPushSubscription,
		arg.UserID,
		arg.Endpoint,
		arg.P256dh,
		arg.Auth,
	)
	return err
}
