// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	// Per-account transaction sums using the same definitions as the register
	// header: future = all, today = dated on/before today, bank = cleared(1) or
	// reconciled(2). The application adds each account's initial balance.
	AccountBalanceDeltas(ctx context.Context, arg AccountBalanceDeltasParams) ([]AccountBalanceDeltasRow, error)
	AddTransactionTag(ctx context.Context, arg AddTransactionTagParams) error
	AddWalletMember(ctx context.Context, arg AddWalletMemberParams) error
	AdvanceSchedule(ctx context.Context, arg AdvanceScheduleParams) error
	// Category amounts in a date range (plain transactions + split lines), excluding
	// accounts flagged no_budget, with each row's currency so the app can convert.
	CategoryActualsForBudget(ctx context.Context, arg CategoryActualsForBudgetParams) ([]CategoryActualsForBudgetRow, error)
	// Category amounts in a date range, from both plain transactions and split
	// lines, with each row's account currency so the app can convert to base.
	CategoryExpenseTotals(ctx context.Context, arg CategoryExpenseTotalsParams) ([]CategoryExpenseTotalsRow, error)
	ClearWalletBase(ctx context.Context, walletID int64) error
	CountPayeesWithCategory(ctx context.Context, defaultCategoryID sql.NullInt64) (int64, error)
	CountSubcategories(ctx context.Context, parentID sql.NullInt64) (int64, error)
	CountTransactionsForAccount(ctx context.Context, accountID int64) (int64, error)
	CountTransactionsWithCategory(ctx context.Context, categoryID sql.NullInt64) (int64, error)
	CountTransactionsWithPayee(ctx context.Context, payeeID sql.NullInt64) (int64, error)
	CountUsers(ctx context.Context) (int64, error)
	CountWalletCurrencies(ctx context.Context, walletID int64) (int64, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateWallet(ctx context.Context, arg CreateWalletParams) (Wallet, error)
	DeleteAccount(ctx context.Context, id int64) error
	DeleteAssignment(ctx context.Context, id int64) error
	DeleteCategory(ctx context.Context, id int64) error
	DeleteCategoryBudget(ctx context.Context, arg DeleteCategoryBudgetParams) error
	DeleteCurrency(ctx context.Context, id int64) error
	DeleteExpiredSessions(ctx context.Context, expiresAt string) error
	DeletePayee(ctx context.Context, id int64) error
	DeleteSchedule(ctx context.Context, id int64) error
	DeleteSession(ctx context.Context, id string) error
	DeleteSplits(ctx context.Context, transactionID int64) error
	DeleteTemplate(ctx context.Context, id int64) error
	DeleteTemplateSplits(ctx context.Context, templateID int64) error
	DeleteTransaction(ctx context.Context, id int64) error
	DeleteTransactionTags(ctx context.Context, transactionID int64) error
	DeleteTransfer(ctx context.Context, id int64) error
	DeleteUserSessions(ctx context.Context, userID int64) error
	DeleteWallet(ctx context.Context, id int64) error
	FindDuplicateTransactions(ctx context.Context, arg FindDuplicateTransactionsParams) ([]Transaction, error)
	GetAccount(ctx context.Context, id int64) (Account, error)
	GetAssignment(ctx context.Context, id int64) (Assignment, error)
	GetBaseCurrency(ctx context.Context, walletID int64) (Currency, error)
	GetCategory(ctx context.Context, id int64) (Category, error)
	GetCurrency(ctx context.Context, id int64) (Currency, error)
	GetPayee(ctx context.Context, id int64) (Payee, error)
	GetSchedule(ctx context.Context, id int64) (Schedule, error)
	GetSession(ctx context.Context, id string) (Session, error)
	GetTagByName(ctx context.Context, arg GetTagByNameParams) (Tag, error)
	GetTemplate(ctx context.Context, id int64) (Template, error)
	GetTransaction(ctx context.Context, id int64) (Transaction, error)
	GetTransfer(ctx context.Context, id int64) (Transfer, error)
	GetTransferByTransaction(ctx context.Context, arg GetTransferByTransactionParams) (Transfer, error)
	GetUserByID(ctx context.Context, id int64) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	GetWallet(ctx context.Context, id int64) (Wallet, error)
	GetWalletMembership(ctx context.Context, arg GetWalletMembershipParams) (string, error)
	InsertAccount(ctx context.Context, arg InsertAccountParams) (Account, error)
	InsertAssignment(ctx context.Context, arg InsertAssignmentParams) (Assignment, error)
	InsertBudget(ctx context.Context, arg InsertBudgetParams) error
	InsertCategory(ctx context.Context, arg InsertCategoryParams) (Category, error)
	InsertCurrency(ctx context.Context, arg InsertCurrencyParams) (Currency, error)
	InsertPayee(ctx context.Context, arg InsertPayeeParams) (Payee, error)
	InsertSchedule(ctx context.Context, arg InsertScheduleParams) (Schedule, error)
	InsertSplit(ctx context.Context, arg InsertSplitParams) error
	InsertTag(ctx context.Context, arg InsertTagParams) (Tag, error)
	InsertTemplate(ctx context.Context, arg InsertTemplateParams) (Template, error)
	InsertTemplateSplit(ctx context.Context, arg InsertTemplateSplitParams) error
	InsertTransaction(ctx context.Context, arg InsertTransactionParams) (Transaction, error)
	InsertTransfer(ctx context.Context, arg InsertTransferParams) (Transfer, error)
	// The full account ledger ordered chronologically (date, then id) with a
	// server-computed cumulative delta. The application adds the account's initial
	// balance to produce each row's running balance.
	ListAccountRegister(ctx context.Context, accountID int64) ([]ListAccountRegisterRow, error)
	ListAccountsForWallet(ctx context.Context, walletID int64) ([]ListAccountsForWalletRow, error)
	ListAllSchedules(ctx context.Context) ([]Schedule, error)
	ListAllWalletIDs(ctx context.Context) ([]int64, error)
	ListAssignmentsForWallet(ctx context.Context, walletID int64) ([]Assignment, error)
	ListBudgetsForWallet(ctx context.Context, walletID int64) ([]Budget, error)
	ListCategoriesForWallet(ctx context.Context, walletID int64) ([]Category, error)
	ListCurrenciesForWallet(ctx context.Context, walletID int64) ([]Currency, error)
	ListExchangeRates(ctx context.Context, currencyID int64) ([]ExchangeRate, error)
	ListImportRefsForAccount(ctx context.Context, accountID int64) ([]string, error)
	ListPayeesForWallet(ctx context.Context, walletID int64) ([]Payee, error)
	ListSchedulesForWallet(ctx context.Context, walletID int64) ([]ListSchedulesForWalletRow, error)
	ListSplits(ctx context.Context, transactionID int64) ([]Split, error)
	ListTagsForWallet(ctx context.Context, walletID int64) ([]Tag, error)
	ListTemplateSplits(ctx context.Context, templateID int64) ([]TemplateSplit, error)
	ListTemplatesForWallet(ctx context.Context, walletID int64) ([]Template, error)
	ListTransactionTags(ctx context.Context, transactionID int64) ([]string, error)
	ListTransactionsForAccount(ctx context.Context, arg ListTransactionsForAccountParams) ([]ListTransactionsForAccountRow, error)
	ListTransfersForWallet(ctx context.Context, walletID int64) ([]Transfer, error)
	ListUpcomingSchedules(ctx context.Context, arg ListUpcomingSchedulesParams) ([]ListUpcomingSchedulesRow, error)
	ListUsers(ctx context.Context) ([]User, error)
	// Fuel transactions for a vehicle category in a date range, with the account
	// currency so costs can be converted to base. Ordered for sequential odometer
	// processing.
	ListVehicleTransactions(ctx context.Context, arg ListVehicleTransactionsParams) ([]ListVehicleTransactionsRow, error)
	ListWalletTransactionsForRules(ctx context.Context, walletID int64) ([]ListWalletTransactionsForRulesRow, error)
	ListWalletsForUser(ctx context.Context, userID int64) ([]ListWalletsForUserRow, error)
	NextAccountPosition(ctx context.Context, walletID int64) (int64, error)
	NextAssignmentPosition(ctx context.Context, walletID int64) (int64, error)
	ReassignPayeeCategory(ctx context.Context, arg ReassignPayeeCategoryParams) error
	ReassignSplitCategory(ctx context.Context, arg ReassignSplitCategoryParams) error
	ReassignTransactionCategory(ctx context.Context, arg ReassignTransactionCategoryParams) error
	ReassignTransactionPayee(ctx context.Context, arg ReassignTransactionPayeeParams) error
	ReparentChildren(ctx context.Context, arg ReparentChildrenParams) error
	SetAssignmentPosition(ctx context.Context, arg SetAssignmentPositionParams) error
	SetChildrenIncome(ctx context.Context, arg SetChildrenIncomeParams) error
	SetCurrencyBase(ctx context.Context, id int64) error
	SetTransactionCategory(ctx context.Context, arg SetTransactionCategoryParams) error
	SetTransactionPayee(ctx context.Context, arg SetTransactionPayeeParams) error
	SetTransactionPaymentMode(ctx context.Context, arg SetTransactionPaymentModeParams) error
	SetTransactionTemplate(ctx context.Context, arg SetTransactionTemplateParams) error
	SetUserDisabled(ctx context.Context, arg SetUserDisabledParams) error
	TouchSession(ctx context.Context, arg TouchSessionParams) error
	UpdateAccount(ctx context.Context, arg UpdateAccountParams) error
	UpdateAccountPosition(ctx context.Context, arg UpdateAccountPositionParams) error
	UpdateAssignment(ctx context.Context, arg UpdateAssignmentParams) error
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) error
	UpdateCurrencyFormat(ctx context.Context, arg UpdateCurrencyFormatParams) error
	UpdateCurrencyRate(ctx context.Context, arg UpdateCurrencyRateParams) error
	UpdatePayee(ctx context.Context, arg UpdatePayeeParams) error
	UpdateScheduleConfig(ctx context.Context, arg UpdateScheduleConfigParams) error
	UpdateTemplate(ctx context.Context, arg UpdateTemplateParams) error
	UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) error
	UpdateTransactionStatus(ctx context.Context, arg UpdateTransactionStatusParams) error
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UpdateUserSettings(ctx context.Context, arg UpdateUserSettingsParams) error
	UpdateWallet(ctx context.Context, arg UpdateWalletParams) error
	UpdateWalletBaseCurrency(ctx context.Context, arg UpdateWalletBaseCurrencyParams) error
	UpsertExchangeRate(ctx context.Context, arg UpsertExchangeRateParams) error
}

var _ Querier = (*Queries)(nil)
