// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reports.sql

package db

import (
	"context"
	"database/sql"
)

const listVehicleTransactions = `-- name: ListVehicleTransactions :many
SELECT t.id, t.date, t.memo, t.amount, a.currency_id
FROM transactions t
JOIN accounts a ON a.id = t.account_id
WHERE t.wallet_id = ?
  AND t.category_id = ?
  AND t.is_split = 0
  AND t.date >= ?
  AND t.date <= ?
ORDER BY t.date, t.id
`

type ListVehicleTransactionsParams struct {
	WalletID   int64
	CategoryID sql.NullInt64
	Date       string
	Date_2     string
}

type ListVehicleTransactionsRow struct {
	ID         int64
	Date       string
	Memo       string
	Amount     int64
	CurrencyID int64
}

// Fuel transactions for a vehicle category in a date range, with the account
// currency so costs can be converted to base. Ordered for sequential odometer
// processing.
func (q *Queries) ListVehicleTransactions(ctx context.Context, arg ListVehicleTransactionsParams) ([]ListVehicleTransactionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listVehicleTransactions,
		arg.WalletID,
		arg.CategoryID,
		arg.Date,
		arg.Date_2,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVehicleTransactionsRow{}
	for rows.Next() {
		var i ListVehicleTransactionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Date,
			&i.Memo,
			&i.Amount,
			&i.CurrencyID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
