// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: review.sql

package db

import (
	"context"
)

const insertDuplicateDismissal = `-- name: InsertDuplicateDismissal :exec
INSERT INTO duplicate_dismissals (wallet_id, txn_a_id, txn_b_id)
VALUES (?, ?, ?)
ON CONFLICT DO NOTHING
`

type InsertDuplicateDismissalParams struct {
	WalletID int64
	TxnAID   int64
	TxnBID   int64
}

func (q *Queries) InsertDuplicateDismissal(ctx context.Context, arg InsertDuplicateDismissalParams) error {
	_, err := q.db.ExecContext(ctx, insertDuplicateDismissal, arg.WalletID, arg.TxnAID, arg.TxnBID)
	return err
}

const listDuplicateDismissals = `-- name: ListDuplicateDismissals :many
SELECT txn_a_id, txn_b_id FROM duplicate_dismissals WHERE wallet_id = ?
`

type ListDuplicateDismissalsRow struct {
	TxnAID int64
	TxnBID int64
}

func (q *Queries) ListDuplicateDismissals(ctx context.Context, walletID int64) ([]ListDuplicateDismissalsRow, error) {
	rows, err := q.db.QueryContext(ctx, listDuplicateDismissals, walletID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDuplicateDismissalsRow{}
	for rows.Next() {
		var i ListDuplicateDismissalsRow
		if err := rows.Scan(&i.TxnAID, &i.TxnBID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listImportedUncategorized = `-- name: ListImportedUncategorized :many
SELECT id, wallet_id, account_id, date, amount, payment_mode, status, info, payee_id, category_id, memo, is_split, created_at, updated_at, template_id, import_ref, vehicle_id
FROM transactions
WHERE wallet_id = ? AND import_ref <> '' AND category_id IS NULL AND is_split = 0
ORDER BY date DESC, id DESC
`

// Bank-imported transactions (they carry an import ref) that still have no
// category, so the review can prompt the user to complete them. Split
// transactions carry their categories on the splits, so they are excluded.
func (q *Queries) ListImportedUncategorized(ctx context.Context, walletID int64) ([]Transaction, error) {
	rows, err := q.db.QueryContext(ctx, listImportedUncategorized, walletID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.WalletID,
			&i.AccountID,
			&i.Date,
			&i.Amount,
			&i.PaymentMode,
			&i.Status,
			&i.Info,
			&i.PayeeID,
			&i.CategoryID,
			&i.Memo,
			&i.IsSplit,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TemplateID,
			&i.ImportRef,
			&i.VehicleID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPotentialDuplicates = `-- name: ListPotentialDuplicates :many
SELECT t.id, t.wallet_id, t.account_id, t.date, t.amount, t.payment_mode, t.status, t.info, t.payee_id, t.category_id, t.memo, t.is_split, t.created_at, t.updated_at, t.template_id, t.import_ref, t.vehicle_id
FROM transactions t
JOIN (
    SELECT g0.account_id AS account_id, g0.amount AS amount
    FROM transactions g0
    WHERE g0.wallet_id = ?
    GROUP BY g0.account_id, g0.amount
    HAVING COUNT(*) > 1
) g ON t.account_id = g.account_id AND t.amount = g.amount
WHERE t.wallet_id = ?
ORDER BY t.account_id, t.amount, t.date, t.id
`

type ListPotentialDuplicatesParams struct {
	WalletID   int64
	WalletID_2 int64
}

// Transactions that share account + amount with at least one other in the wallet.
// Pairing by date proximity and filtering out dismissed pairs is done in Go.
func (q *Queries) ListPotentialDuplicates(ctx context.Context, arg ListPotentialDuplicatesParams) ([]Transaction, error) {
	rows, err := q.db.QueryContext(ctx, listPotentialDuplicates, arg.WalletID, arg.WalletID_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.WalletID,
			&i.AccountID,
			&i.Date,
			&i.Amount,
			&i.PaymentMode,
			&i.Status,
			&i.Info,
			&i.PayeeID,
			&i.CategoryID,
			&i.Memo,
			&i.IsSplit,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TemplateID,
			&i.ImportRef,
			&i.VehicleID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setTransactionImportRef = `-- name: SetTransactionImportRef :exec
UPDATE transactions SET import_ref = ? WHERE id = ? AND wallet_id = ?
`

type SetTransactionImportRefParams struct {
	ImportRef string
	ID        int64
	WalletID  int64
}

func (q *Queries) SetTransactionImportRef(ctx context.Context, arg SetTransactionImportRefParams) error {
	_, err := q.db.ExecContext(ctx, setTransactionImportRef, arg.ImportRef, arg.ID, arg.WalletID)
	return err
}
