// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: review.sql

package db

import (
	"context"
	"strings"
)

const insertDuplicateDismissal = `-- name: InsertDuplicateDismissal :exec
INSERT INTO duplicate_dismissals (wallet_id, txn_a_id, txn_b_id)
VALUES (?, ?, ?)
ON CONFLICT DO NOTHING
`

type InsertDuplicateDismissalParams struct {
	WalletID int64
	TxnAID   int64
	TxnBID   int64
}

func (q *Queries) InsertDuplicateDismissal(ctx context.Context, arg InsertDuplicateDismissalParams) error {
	_, err := q.db.ExecContext(ctx, insertDuplicateDismissal, arg.WalletID, arg.TxnAID, arg.TxnBID)
	return err
}

const listDuplicateCandidates = `-- name: ListDuplicateCandidates :many
SELECT n.id, n.account_id, n.amount, n.date
FROM accounts a
JOIN transactions n ON n.account_id = a.id
WHERE a.wallet_id = ?
ORDER BY n.account_id, n.amount, n.date, n.id
`

type ListDuplicateCandidatesRow struct {
	ID        int64
	AccountID int64
	Amount    int64
	Date      string
}

// Every transaction of the wallet, reduced to what the duplicate finder compares
// and ordered for it: by account, amount, then date. The account/date index
// holds all four columns, so this reads no table rows (#541).
func (q *Queries) ListDuplicateCandidates(ctx context.Context, walletID int64) ([]ListDuplicateCandidatesRow, error) {
	rows, err := q.db.QueryContext(ctx, listDuplicateCandidates, walletID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDuplicateCandidatesRow{}
	for rows.Next() {
		var i ListDuplicateCandidatesRow
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Amount,
			&i.Date,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDuplicateDismissals = `-- name: ListDuplicateDismissals :many
SELECT txn_a_id, txn_b_id FROM duplicate_dismissals WHERE wallet_id = ?
`

type ListDuplicateDismissalsRow struct {
	TxnAID int64
	TxnBID int64
}

func (q *Queries) ListDuplicateDismissals(ctx context.Context, walletID int64) ([]ListDuplicateDismissalsRow, error) {
	rows, err := q.db.QueryContext(ctx, listDuplicateDismissals, walletID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDuplicateDismissalsRow{}
	for rows.Next() {
		var i ListDuplicateDismissalsRow
		if err := rows.Scan(&i.TxnAID, &i.TxnBID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listImportedUncategorized = `-- name: ListImportedUncategorized :many
SELECT id, wallet_id, account_id, date, amount, payment_mode, status, info, payee_id, category_id, memo, is_split, created_at, updated_at, template_id, import_ref, vehicle_id
FROM transactions
WHERE wallet_id = ? AND import_ref <> '' AND category_id IS NULL AND is_split = 0
ORDER BY date DESC, id DESC
`

// Bank-imported transactions (they carry an import ref) that still have no
// category, so the review can prompt the user to complete them. Split
// transactions carry their categories on the splits, so they are excluded.
func (q *Queries) ListImportedUncategorized(ctx context.Context, walletID int64) ([]Transaction, error) {
	rows, err := q.db.QueryContext(ctx, listImportedUncategorized, walletID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.WalletID,
			&i.AccountID,
			&i.Date,
			&i.Amount,
			&i.PaymentMode,
			&i.Status,
			&i.Info,
			&i.PayeeID,
			&i.CategoryID,
			&i.Memo,
			&i.IsSplit,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TemplateID,
			&i.ImportRef,
			&i.VehicleID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsByIDs = `-- name: ListTransactionsByIDs :many
SELECT id, wallet_id, account_id, date, amount, payment_mode, status, info, payee_id, category_id, memo, is_split, created_at, updated_at, template_id, import_ref, vehicle_id FROM transactions
WHERE wallet_id = ?1 AND id IN (/*SLICE:ids*/?)
`

type ListTransactionsByIDsParams struct {
	WalletID int64
	Ids      []int64
}

func (q *Queries) ListTransactionsByIDs(ctx context.Context, arg ListTransactionsByIDsParams) ([]Transaction, error) {
	query := listTransactionsByIDs
	var queryParams []interface{}
	queryParams = append(queryParams, arg.WalletID)
	if len(arg.Ids) > 0 {
		for _, v := range arg.Ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(arg.Ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.WalletID,
			&i.AccountID,
			&i.Date,
			&i.Amount,
			&i.PaymentMode,
			&i.Status,
			&i.Info,
			&i.PayeeID,
			&i.CategoryID,
			&i.Memo,
			&i.IsSplit,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TemplateID,
			&i.ImportRef,
			&i.VehicleID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setTransactionImportRef = `-- name: SetTransactionImportRef :exec
UPDATE transactions SET import_ref = ? WHERE id = ? AND wallet_id = ?
`

type SetTransactionImportRefParams struct {
	ImportRef string
	ID        int64
	WalletID  int64
}

func (q *Queries) SetTransactionImportRef(ctx context.Context, arg SetTransactionImportRefParams) error {
	_, err := q.db.ExecContext(ctx, setTransactionImportRef, arg.ImportRef, arg.ID, arg.WalletID)
	return err
}
