// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: schedules.sql

package db

import (
	"context"
	"database/sql"
)

const advanceSchedule = `-- name: AdvanceSchedule :exec
UPDATE schedules SET next_due = ?, remaining = ?, last_posted = ? WHERE id = ?
`

type AdvanceScheduleParams struct {
	NextDue    string
	Remaining  sql.NullInt64
	LastPosted sql.NullString
	ID         int64
}

func (q *Queries) AdvanceSchedule(ctx context.Context, arg AdvanceScheduleParams) error {
	_, err := q.db.ExecContext(ctx, advanceSchedule,
		arg.NextDue,
		arg.Remaining,
		arg.LastPosted,
		arg.ID,
	)
	return err
}

const deleteSchedule = `-- name: DeleteSchedule :exec
DELETE FROM schedules WHERE id = ?
`

func (q *Queries) DeleteSchedule(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteSchedule, id)
	return err
}

const getSchedule = `-- name: GetSchedule :one
SELECT id, wallet_id, template_id, unit, every_n, next_due, weekend_mode, remaining, post_advance, auto_post, last_posted, created_at FROM schedules WHERE id = ? LIMIT 1
`

func (q *Queries) GetSchedule(ctx context.Context, id int64) (Schedule, error) {
	row := q.db.QueryRowContext(ctx, getSchedule, id)
	var i Schedule
	err := row.Scan(
		&i.ID,
		&i.WalletID,
		&i.TemplateID,
		&i.Unit,
		&i.EveryN,
		&i.NextDue,
		&i.WeekendMode,
		&i.Remaining,
		&i.PostAdvance,
		&i.AutoPost,
		&i.LastPosted,
		&i.CreatedAt,
	)
	return i, err
}

const insertSchedule = `-- name: InsertSchedule :one
INSERT INTO schedules (
    wallet_id, template_id, unit, every_n, next_due, weekend_mode,
    remaining, post_advance, auto_post
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, wallet_id, template_id, unit, every_n, next_due, weekend_mode, remaining, post_advance, auto_post, last_posted, created_at
`

type InsertScheduleParams struct {
	WalletID    int64
	TemplateID  int64
	Unit        string
	EveryN      int64
	NextDue     string
	WeekendMode int64
	Remaining   sql.NullInt64
	PostAdvance int64
	AutoPost    int64
}

func (q *Queries) InsertSchedule(ctx context.Context, arg InsertScheduleParams) (Schedule, error) {
	row := q.db.QueryRowContext(ctx, insertSchedule,
		arg.WalletID,
		arg.TemplateID,
		arg.Unit,
		arg.EveryN,
		arg.NextDue,
		arg.WeekendMode,
		arg.Remaining,
		arg.PostAdvance,
		arg.AutoPost,
	)
	var i Schedule
	err := row.Scan(
		&i.ID,
		&i.WalletID,
		&i.TemplateID,
		&i.Unit,
		&i.EveryN,
		&i.NextDue,
		&i.WeekendMode,
		&i.Remaining,
		&i.PostAdvance,
		&i.AutoPost,
		&i.LastPosted,
		&i.CreatedAt,
	)
	return i, err
}

const listAllSchedules = `-- name: ListAllSchedules :many
SELECT id, wallet_id, template_id, unit, every_n, next_due, weekend_mode, remaining, post_advance, auto_post, last_posted, created_at FROM schedules ORDER BY id
`

func (q *Queries) ListAllSchedules(ctx context.Context) ([]Schedule, error) {
	rows, err := q.db.QueryContext(ctx, listAllSchedules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Schedule{}
	for rows.Next() {
		var i Schedule
		if err := rows.Scan(
			&i.ID,
			&i.WalletID,
			&i.TemplateID,
			&i.Unit,
			&i.EveryN,
			&i.NextDue,
			&i.WeekendMode,
			&i.Remaining,
			&i.PostAdvance,
			&i.AutoPost,
			&i.LastPosted,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSchedulesForWallet = `-- name: ListSchedulesForWallet :many
SELECT sch.id, sch.wallet_id, sch.template_id, sch.unit, sch.every_n, sch.next_due, sch.weekend_mode, sch.remaining, sch.post_advance, sch.auto_post, sch.last_posted, sch.created_at, tpl.name AS template_name, tpl.amount AS template_amount,
       tpl.is_transfer AS template_is_transfer
FROM schedules sch
JOIN templates tpl ON tpl.id = sch.template_id
WHERE sch.wallet_id = ?
ORDER BY sch.next_due, sch.id
`

type ListSchedulesForWalletRow struct {
	ID                 int64
	WalletID           int64
	TemplateID         int64
	Unit               string
	EveryN             int64
	NextDue            string
	WeekendMode        int64
	Remaining          sql.NullInt64
	PostAdvance        int64
	AutoPost           int64
	LastPosted         sql.NullString
	CreatedAt          string
	TemplateName       string
	TemplateAmount     int64
	TemplateIsTransfer int64
}

func (q *Queries) ListSchedulesForWallet(ctx context.Context, walletID int64) ([]ListSchedulesForWalletRow, error) {
	rows, err := q.db.QueryContext(ctx, listSchedulesForWallet, walletID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSchedulesForWalletRow{}
	for rows.Next() {
		var i ListSchedulesForWalletRow
		if err := rows.Scan(
			&i.ID,
			&i.WalletID,
			&i.TemplateID,
			&i.Unit,
			&i.EveryN,
			&i.NextDue,
			&i.WeekendMode,
			&i.Remaining,
			&i.PostAdvance,
			&i.AutoPost,
			&i.LastPosted,
			&i.CreatedAt,
			&i.TemplateName,
			&i.TemplateAmount,
			&i.TemplateIsTransfer,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUpcomingSchedules = `-- name: ListUpcomingSchedules :many
SELECT sch.id, sch.wallet_id, sch.template_id, sch.unit, sch.every_n, sch.next_due, sch.weekend_mode, sch.remaining, sch.post_advance, sch.auto_post, sch.last_posted, sch.created_at, tpl.name AS template_name, tpl.amount AS template_amount,
       tpl.is_transfer AS template_is_transfer
FROM schedules sch
JOIN templates tpl ON tpl.id = sch.template_id
WHERE sch.wallet_id = ? AND sch.next_due <= ?
ORDER BY sch.next_due, sch.id
`

type ListUpcomingSchedulesParams struct {
	WalletID int64
	NextDue  string
}

type ListUpcomingSchedulesRow struct {
	ID                 int64
	WalletID           int64
	TemplateID         int64
	Unit               string
	EveryN             int64
	NextDue            string
	WeekendMode        int64
	Remaining          sql.NullInt64
	PostAdvance        int64
	AutoPost           int64
	LastPosted         sql.NullString
	CreatedAt          string
	TemplateName       string
	TemplateAmount     int64
	TemplateIsTransfer int64
}

func (q *Queries) ListUpcomingSchedules(ctx context.Context, arg ListUpcomingSchedulesParams) ([]ListUpcomingSchedulesRow, error) {
	rows, err := q.db.QueryContext(ctx, listUpcomingSchedules, arg.WalletID, arg.NextDue)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUpcomingSchedulesRow{}
	for rows.Next() {
		var i ListUpcomingSchedulesRow
		if err := rows.Scan(
			&i.ID,
			&i.WalletID,
			&i.TemplateID,
			&i.Unit,
			&i.EveryN,
			&i.NextDue,
			&i.WeekendMode,
			&i.Remaining,
			&i.PostAdvance,
			&i.AutoPost,
			&i.LastPosted,
			&i.CreatedAt,
			&i.TemplateName,
			&i.TemplateAmount,
			&i.TemplateIsTransfer,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateScheduleConfig = `-- name: UpdateScheduleConfig :exec
UPDATE schedules SET
    unit = ?, every_n = ?, next_due = ?, weekend_mode = ?,
    remaining = ?, post_advance = ?, auto_post = ?
WHERE id = ?
`

type UpdateScheduleConfigParams struct {
	Unit        string
	EveryN      int64
	NextDue     string
	WeekendMode int64
	Remaining   sql.NullInt64
	PostAdvance int64
	AutoPost    int64
	ID          int64
}

func (q *Queries) UpdateScheduleConfig(ctx context.Context, arg UpdateScheduleConfigParams) error {
	_, err := q.db.ExecContext(ctx, updateScheduleConfig,
		arg.Unit,
		arg.EveryN,
		arg.NextDue,
		arg.WeekendMode,
		arg.Remaining,
		arg.PostAdvance,
		arg.AutoPost,
		arg.ID,
	)
	return err
}
