// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: splits.sql

package db

import (
	"context"
	"database/sql"
)

const deleteSplits = `-- name: DeleteSplits :exec
DELETE FROM splits WHERE transaction_id = ?
`

func (q *Queries) DeleteSplits(ctx context.Context, transactionID int64) error {
	_, err := q.db.ExecContext(ctx, deleteSplits, transactionID)
	return err
}

const insertSplit = `-- name: InsertSplit :exec
INSERT INTO splits (transaction_id, category_id, amount, memo, position)
VALUES (?, ?, ?, ?, ?)
`

type InsertSplitParams struct {
	TransactionID int64
	CategoryID    sql.NullInt64
	Amount        int64
	Memo          string
	Position      int64
}

func (q *Queries) InsertSplit(ctx context.Context, arg InsertSplitParams) error {
	_, err := q.db.ExecContext(ctx, insertSplit,
		arg.TransactionID,
		arg.CategoryID,
		arg.Amount,
		arg.Memo,
		arg.Position,
	)
	return err
}

const listSplits = `-- name: ListSplits :many
SELECT id, transaction_id, category_id, amount, memo, position FROM splits WHERE transaction_id = ? ORDER BY position, id
`

func (q *Queries) ListSplits(ctx context.Context, transactionID int64) ([]Split, error) {
	rows, err := q.db.QueryContext(ctx, listSplits, transactionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Split{}
	for rows.Next() {
		var i Split
		if err := rows.Scan(
			&i.ID,
			&i.TransactionID,
			&i.CategoryID,
			&i.Amount,
			&i.Memo,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
