// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: templates.sql

package db

import (
	"context"
	"database/sql"
)

const countTemplateSchedules = `-- name: CountTemplateSchedules :one
SELECT COUNT(*) FROM schedules WHERE template_id = ?
`

func (q *Queries) CountTemplateSchedules(ctx context.Context, templateID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTemplateSchedules, templateID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteTemplate = `-- name: DeleteTemplate :exec
DELETE FROM templates WHERE id = ?
`

func (q *Queries) DeleteTemplate(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTemplate, id)
	return err
}

const deleteTemplateSplits = `-- name: DeleteTemplateSplits :exec
DELETE FROM template_splits WHERE template_id = ?
`

func (q *Queries) DeleteTemplateSplits(ctx context.Context, templateID int64) error {
	_, err := q.db.ExecContext(ctx, deleteTemplateSplits, templateID)
	return err
}

const getTemplate = `-- name: GetTemplate :one
SELECT id, wallet_id, name, account_id, amount, payment_mode, status, info, payee_id, category_id, memo, tags, is_split, is_transfer, to_account_id, created_at FROM templates WHERE id = ? LIMIT 1
`

func (q *Queries) GetTemplate(ctx context.Context, id int64) (Template, error) {
	row := q.db.QueryRowContext(ctx, getTemplate, id)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.WalletID,
		&i.Name,
		&i.AccountID,
		&i.Amount,
		&i.PaymentMode,
		&i.Status,
		&i.Info,
		&i.PayeeID,
		&i.CategoryID,
		&i.Memo,
		&i.Tags,
		&i.IsSplit,
		&i.IsTransfer,
		&i.ToAccountID,
		&i.CreatedAt,
	)
	return i, err
}

const insertTemplate = `-- name: InsertTemplate :one
INSERT INTO templates (
    wallet_id, name, account_id, amount, payment_mode, status, info,
    payee_id, category_id, memo, tags, is_split, is_transfer, to_account_id
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, wallet_id, name, account_id, amount, payment_mode, status, info, payee_id, category_id, memo, tags, is_split, is_transfer, to_account_id, created_at
`

type InsertTemplateParams struct {
	WalletID    int64
	Name        string
	AccountID   sql.NullInt64
	Amount      int64
	PaymentMode int64
	Status      int64
	Info        string
	PayeeID     sql.NullInt64
	CategoryID  sql.NullInt64
	Memo        string
	Tags        string
	IsSplit     int64
	IsTransfer  int64
	ToAccountID sql.NullInt64
}

func (q *Queries) InsertTemplate(ctx context.Context, arg InsertTemplateParams) (Template, error) {
	row := q.db.QueryRowContext(ctx, insertTemplate,
		arg.WalletID,
		arg.Name,
		arg.AccountID,
		arg.Amount,
		arg.PaymentMode,
		arg.Status,
		arg.Info,
		arg.PayeeID,
		arg.CategoryID,
		arg.Memo,
		arg.Tags,
		arg.IsSplit,
		arg.IsTransfer,
		arg.ToAccountID,
	)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.WalletID,
		&i.Name,
		&i.AccountID,
		&i.Amount,
		&i.PaymentMode,
		&i.Status,
		&i.Info,
		&i.PayeeID,
		&i.CategoryID,
		&i.Memo,
		&i.Tags,
		&i.IsSplit,
		&i.IsTransfer,
		&i.ToAccountID,
		&i.CreatedAt,
	)
	return i, err
}

const insertTemplateSplit = `-- name: InsertTemplateSplit :exec
INSERT INTO template_splits (template_id, category_id, amount, memo, position)
VALUES (?, ?, ?, ?, ?)
`

type InsertTemplateSplitParams struct {
	TemplateID int64
	CategoryID sql.NullInt64
	Amount     int64
	Memo       string
	Position   int64
}

func (q *Queries) InsertTemplateSplit(ctx context.Context, arg InsertTemplateSplitParams) error {
	_, err := q.db.ExecContext(ctx, insertTemplateSplit,
		arg.TemplateID,
		arg.CategoryID,
		arg.Amount,
		arg.Memo,
		arg.Position,
	)
	return err
}

const linkTemplateTransactions = `-- name: LinkTemplateTransactions :execrows
UPDATE transactions SET template_id = ?1
WHERE template_id IS NULL
  AND wallet_id = (SELECT tpl.wallet_id FROM templates tpl WHERE tpl.id = ?1)
  AND account_id = (SELECT tpl.account_id FROM templates tpl WHERE tpl.id = ?1)
  AND payee_id = (SELECT tpl.payee_id FROM templates tpl WHERE tpl.id = ?1)
  AND category_id = (SELECT tpl.category_id FROM templates tpl WHERE tpl.id = ?1)
`

// Ties to a template the transactions it stands for that were written without
// the link: same account, payee and category. The demo's seeded year comes
// from a HomeBank file, which does not record which schedule posted what.
func (q *Queries) LinkTemplateTransactions(ctx context.Context, templateID sql.NullInt64) (int64, error) {
	result, err := q.db.ExecContext(ctx, linkTemplateTransactions, templateID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listTemplateSplits = `-- name: ListTemplateSplits :many
SELECT id, template_id, category_id, amount, memo, position FROM template_splits WHERE template_id = ? ORDER BY position, id
`

func (q *Queries) ListTemplateSplits(ctx context.Context, templateID int64) ([]TemplateSplit, error) {
	rows, err := q.db.QueryContext(ctx, listTemplateSplits, templateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TemplateSplit{}
	for rows.Next() {
		var i TemplateSplit
		if err := rows.Scan(
			&i.ID,
			&i.TemplateID,
			&i.CategoryID,
			&i.Amount,
			&i.Memo,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTemplatesForWallet = `-- name: ListTemplatesForWallet :many
SELECT id, wallet_id, name, account_id, amount, payment_mode, status, info, payee_id, category_id, memo, tags, is_split, is_transfer, to_account_id, created_at FROM templates WHERE wallet_id = ? ORDER BY name COLLATE NOCASE
`

func (q *Queries) ListTemplatesForWallet(ctx context.Context, walletID int64) ([]Template, error) {
	rows, err := q.db.QueryContext(ctx, listTemplatesForWallet, walletID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Template{}
	for rows.Next() {
		var i Template
		if err := rows.Scan(
			&i.ID,
			&i.WalletID,
			&i.Name,
			&i.AccountID,
			&i.Amount,
			&i.PaymentMode,
			&i.Status,
			&i.Info,
			&i.PayeeID,
			&i.CategoryID,
			&i.Memo,
			&i.Tags,
			&i.IsSplit,
			&i.IsTransfer,
			&i.ToAccountID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const templateUsage = `-- name: TemplateUsage :many
SELECT t.template_id AS template_id,
       CAST(SUM(CASE WHEN t.date >= ?1 THEN 1 ELSE 0 END) AS INTEGER) AS txn_count,
       CAST(MAX(t.date) AS TEXT) AS last_date
FROM transactions t
JOIN templates tpl ON tpl.id = t.template_id
WHERE t.wallet_id = ?2
  AND t.date <= ?3
  AND (tpl.account_id IS NULL OR t.account_id = tpl.account_id)
GROUP BY t.template_id
`

type TemplateUsageParams struct {
	FromDate string
	WalletID int64
	ToDate   string
}

type TemplateUsageRow struct {
	TemplateID sql.NullInt64
	TxnCount   int64
	LastDate   string
}

// How often each template was used: the transactions made from it dated in
// [from_date, to_date], and the latest on or before to_date (#560). A transfer
// counts once, by its leg on the template's own account.
func (q *Queries) TemplateUsage(ctx context.Context, arg TemplateUsageParams) ([]TemplateUsageRow, error) {
	rows, err := q.db.QueryContext(ctx, templateUsage, arg.FromDate, arg.WalletID, arg.ToDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TemplateUsageRow{}
	for rows.Next() {
		var i TemplateUsageRow
		if err := rows.Scan(&i.TemplateID, &i.TxnCount, &i.LastDate); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTemplate = `-- name: UpdateTemplate :exec
UPDATE templates SET
    name = ?, account_id = ?, amount = ?, payment_mode = ?, status = ?, info = ?,
    payee_id = ?, category_id = ?, memo = ?, tags = ?, is_split = ?,
    is_transfer = ?, to_account_id = ?
WHERE id = ?
`

type UpdateTemplateParams struct {
	Name        string
	AccountID   sql.NullInt64
	Amount      int64
	PaymentMode int64
	Status      int64
	Info        string
	PayeeID     sql.NullInt64
	CategoryID  sql.NullInt64
	Memo        string
	Tags        string
	IsSplit     int64
	IsTransfer  int64
	ToAccountID sql.NullInt64
	ID          int64
}

func (q *Queries) UpdateTemplate(ctx context.Context, arg UpdateTemplateParams) error {
	_, err := q.db.ExecContext(ctx, updateTemplate,
		arg.Name,
		arg.AccountID,
		arg.Amount,
		arg.PaymentMode,
		arg.Status,
		arg.Info,
		arg.PayeeID,
		arg.CategoryID,
		arg.Memo,
		arg.Tags,
		arg.IsSplit,
		arg.IsTransfer,
		arg.ToAccountID,
		arg.ID,
	)
	return err
}
