// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transactions.sql

package db

import (
	"context"
	"database/sql"
)

const countTransactionsForAccount = `-- name: CountTransactionsForAccount :one
SELECT COUNT(*) FROM transactions WHERE account_id = ?
`

func (q *Queries) CountTransactionsForAccount(ctx context.Context, accountID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTransactionsForAccount, accountID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteTransaction = `-- name: DeleteTransaction :exec
DELETE FROM transactions WHERE id = ?
`

func (q *Queries) DeleteTransaction(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTransaction, id)
	return err
}

const findDuplicateTransactions = `-- name: FindDuplicateTransactions :many
SELECT id, wallet_id, account_id, date, amount, payment_mode, status, info, payee_id, category_id, memo, is_split, created_at, updated_at FROM transactions
WHERE account_id = ? AND amount = ? AND date >= ? AND date <= ?
ORDER BY date DESC
`

type FindDuplicateTransactionsParams struct {
	AccountID int64
	Amount    int64
	Date      string
	Date_2    string
}

func (q *Queries) FindDuplicateTransactions(ctx context.Context, arg FindDuplicateTransactionsParams) ([]Transaction, error) {
	rows, err := q.db.QueryContext(ctx, findDuplicateTransactions,
		arg.AccountID,
		arg.Amount,
		arg.Date,
		arg.Date_2,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.WalletID,
			&i.AccountID,
			&i.Date,
			&i.Amount,
			&i.PaymentMode,
			&i.Status,
			&i.Info,
			&i.PayeeID,
			&i.CategoryID,
			&i.Memo,
			&i.IsSplit,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTransaction = `-- name: GetTransaction :one
SELECT id, wallet_id, account_id, date, amount, payment_mode, status, info, payee_id, category_id, memo, is_split, created_at, updated_at FROM transactions WHERE id = ? LIMIT 1
`

func (q *Queries) GetTransaction(ctx context.Context, id int64) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, getTransaction, id)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.WalletID,
		&i.AccountID,
		&i.Date,
		&i.Amount,
		&i.PaymentMode,
		&i.Status,
		&i.Info,
		&i.PayeeID,
		&i.CategoryID,
		&i.Memo,
		&i.IsSplit,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertTransaction = `-- name: InsertTransaction :one
INSERT INTO transactions (
    wallet_id, account_id, date, amount, payment_mode, status, info,
    payee_id, category_id, memo, is_split
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, wallet_id, account_id, date, amount, payment_mode, status, info, payee_id, category_id, memo, is_split, created_at, updated_at
`

type InsertTransactionParams struct {
	WalletID    int64
	AccountID   int64
	Date        string
	Amount      int64
	PaymentMode int64
	Status      int64
	Info        string
	PayeeID     sql.NullInt64
	CategoryID  sql.NullInt64
	Memo        string
	IsSplit     int64
}

func (q *Queries) InsertTransaction(ctx context.Context, arg InsertTransactionParams) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, insertTransaction,
		arg.WalletID,
		arg.AccountID,
		arg.Date,
		arg.Amount,
		arg.PaymentMode,
		arg.Status,
		arg.Info,
		arg.PayeeID,
		arg.CategoryID,
		arg.Memo,
		arg.IsSplit,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.WalletID,
		&i.AccountID,
		&i.Date,
		&i.Amount,
		&i.PaymentMode,
		&i.Status,
		&i.Info,
		&i.PayeeID,
		&i.CategoryID,
		&i.Memo,
		&i.IsSplit,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTransactionsForAccount = `-- name: ListTransactionsForAccount :many
SELECT t.id, t.wallet_id, t.account_id, t.date, t.amount, t.payment_mode, t.status, t.info, t.payee_id, t.category_id, t.memo, t.is_split, t.created_at, t.updated_at, p.name AS payee_name, c.name AS category_name
FROM transactions t
LEFT JOIN payees p ON p.id = t.payee_id
LEFT JOIN categories c ON c.id = t.category_id
WHERE t.account_id = ?
ORDER BY t.date DESC, t.id DESC
LIMIT ? OFFSET ?
`

type ListTransactionsForAccountParams struct {
	AccountID int64
	Limit     int64
	Offset    int64
}

type ListTransactionsForAccountRow struct {
	ID           int64
	WalletID     int64
	AccountID    int64
	Date         string
	Amount       int64
	PaymentMode  int64
	Status       int64
	Info         string
	PayeeID      sql.NullInt64
	CategoryID   sql.NullInt64
	Memo         string
	IsSplit      int64
	CreatedAt    string
	UpdatedAt    string
	PayeeName    sql.NullString
	CategoryName sql.NullString
}

func (q *Queries) ListTransactionsForAccount(ctx context.Context, arg ListTransactionsForAccountParams) ([]ListTransactionsForAccountRow, error) {
	rows, err := q.db.QueryContext(ctx, listTransactionsForAccount, arg.AccountID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTransactionsForAccountRow{}
	for rows.Next() {
		var i ListTransactionsForAccountRow
		if err := rows.Scan(
			&i.ID,
			&i.WalletID,
			&i.AccountID,
			&i.Date,
			&i.Amount,
			&i.PaymentMode,
			&i.Status,
			&i.Info,
			&i.PayeeID,
			&i.CategoryID,
			&i.Memo,
			&i.IsSplit,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PayeeName,
			&i.CategoryName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTransaction = `-- name: UpdateTransaction :exec
UPDATE transactions SET
    date = ?, amount = ?, payment_mode = ?, status = ?, info = ?,
    payee_id = ?, category_id = ?, memo = ?, is_split = ?,
    updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ?
`

type UpdateTransactionParams struct {
	Date        string
	Amount      int64
	PaymentMode int64
	Status      int64
	Info        string
	PayeeID     sql.NullInt64
	CategoryID  sql.NullInt64
	Memo        string
	IsSplit     int64
	ID          int64
}

func (q *Queries) UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) error {
	_, err := q.db.ExecContext(ctx, updateTransaction,
		arg.Date,
		arg.Amount,
		arg.PaymentMode,
		arg.Status,
		arg.Info,
		arg.PayeeID,
		arg.CategoryID,
		arg.Memo,
		arg.IsSplit,
		arg.ID,
	)
	return err
}
