// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transactions.sql

package db

import (
	"context"
	"database/sql"
)

const countTransactionsForAccount = `-- name: CountTransactionsForAccount :one
SELECT COUNT(*) FROM transactions WHERE account_id = ?
`

func (q *Queries) CountTransactionsForAccount(ctx context.Context, accountID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTransactionsForAccount, accountID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteTransaction = `-- name: DeleteTransaction :exec
DELETE FROM transactions WHERE id = ?
`

func (q *Queries) DeleteTransaction(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTransaction, id)
	return err
}

const findDuplicateTransactions = `-- name: FindDuplicateTransactions :many
SELECT id, wallet_id, account_id, date, amount, payment_mode, status, info, payee_id, category_id, memo, is_split, created_at, updated_at FROM transactions
WHERE account_id = ? AND amount = ? AND date >= ? AND date <= ?
ORDER BY date DESC
`

type FindDuplicateTransactionsParams struct {
	AccountID int64
	Amount    int64
	Date      string
	Date_2    string
}

func (q *Queries) FindDuplicateTransactions(ctx context.Context, arg FindDuplicateTransactionsParams) ([]Transaction, error) {
	rows, err := q.db.QueryContext(ctx, findDuplicateTransactions,
		arg.AccountID,
		arg.Amount,
		arg.Date,
		arg.Date_2,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.WalletID,
			&i.AccountID,
			&i.Date,
			&i.Amount,
			&i.PaymentMode,
			&i.Status,
			&i.Info,
			&i.PayeeID,
			&i.CategoryID,
			&i.Memo,
			&i.IsSplit,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTransaction = `-- name: GetTransaction :one
SELECT id, wallet_id, account_id, date, amount, payment_mode, status, info, payee_id, category_id, memo, is_split, created_at, updated_at FROM transactions WHERE id = ? LIMIT 1
`

func (q *Queries) GetTransaction(ctx context.Context, id int64) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, getTransaction, id)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.WalletID,
		&i.AccountID,
		&i.Date,
		&i.Amount,
		&i.PaymentMode,
		&i.Status,
		&i.Info,
		&i.PayeeID,
		&i.CategoryID,
		&i.Memo,
		&i.IsSplit,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertTransaction = `-- name: InsertTransaction :one
INSERT INTO transactions (
    wallet_id, account_id, date, amount, payment_mode, status, info,
    payee_id, category_id, memo, is_split
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, wallet_id, account_id, date, amount, payment_mode, status, info, payee_id, category_id, memo, is_split, created_at, updated_at
`

type InsertTransactionParams struct {
	WalletID    int64
	AccountID   int64
	Date        string
	Amount      int64
	PaymentMode int64
	Status      int64
	Info        string
	PayeeID     sql.NullInt64
	CategoryID  sql.NullInt64
	Memo        string
	IsSplit     int64
}

func (q *Queries) InsertTransaction(ctx context.Context, arg InsertTransactionParams) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, insertTransaction,
		arg.WalletID,
		arg.AccountID,
		arg.Date,
		arg.Amount,
		arg.PaymentMode,
		arg.Status,
		arg.Info,
		arg.PayeeID,
		arg.CategoryID,
		arg.Memo,
		arg.IsSplit,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.WalletID,
		&i.AccountID,
		&i.Date,
		&i.Amount,
		&i.PaymentMode,
		&i.Status,
		&i.Info,
		&i.PayeeID,
		&i.CategoryID,
		&i.Memo,
		&i.IsSplit,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAccountRegister = `-- name: ListAccountRegister :many
SELECT
    t.id, t.account_id, t.date, t.amount, t.payment_mode, t.status, t.info,
    t.payee_id, t.category_id, t.memo, t.is_split, t.created_at, t.updated_at,
    p.name AS payee_name,
    c.name AS category_name,
    tr.id AS transfer_id,
    ot.account_id AS transfer_account_id,
    COALESCE((SELECT group_concat(tg.name, ',') FROM transaction_tags tt JOIN tags tg ON tg.id = tt.tag_id WHERE tt.transaction_id = t.id), '') AS tags,
    CAST(SUM(t.amount) OVER (ORDER BY t.date, t.id ROWS UNBOUNDED PRECEDING) AS INTEGER) AS running_delta
FROM transactions t
LEFT JOIN payees p ON p.id = t.payee_id
LEFT JOIN categories c ON c.id = t.category_id
LEFT JOIN transfers tr ON tr.txn_from_id = t.id OR tr.txn_to_id = t.id
LEFT JOIN transactions ot ON ot.id = (CASE WHEN tr.txn_from_id = t.id THEN tr.txn_to_id ELSE tr.txn_from_id END)
WHERE t.account_id = ?
ORDER BY t.date, t.id
`

type ListAccountRegisterRow struct {
	ID                int64
	AccountID         int64
	Date              string
	Amount            int64
	PaymentMode       int64
	Status            int64
	Info              string
	PayeeID           sql.NullInt64
	CategoryID        sql.NullInt64
	Memo              string
	IsSplit           int64
	CreatedAt         string
	UpdatedAt         string
	PayeeName         sql.NullString
	CategoryName      sql.NullString
	TransferID        sql.NullInt64
	TransferAccountID sql.NullInt64
	Tags              interface{}
	RunningDelta      int64
}

// The full account ledger ordered chronologically (date, then id) with a
// server-computed cumulative delta. The application adds the account's initial
// balance to produce each row's running balance.
func (q *Queries) ListAccountRegister(ctx context.Context, accountID int64) ([]ListAccountRegisterRow, error) {
	rows, err := q.db.QueryContext(ctx, listAccountRegister, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAccountRegisterRow{}
	for rows.Next() {
		var i ListAccountRegisterRow
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Date,
			&i.Amount,
			&i.PaymentMode,
			&i.Status,
			&i.Info,
			&i.PayeeID,
			&i.CategoryID,
			&i.Memo,
			&i.IsSplit,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PayeeName,
			&i.CategoryName,
			&i.TransferID,
			&i.TransferAccountID,
			&i.Tags,
			&i.RunningDelta,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsForAccount = `-- name: ListTransactionsForAccount :many
SELECT t.id, t.wallet_id, t.account_id, t.date, t.amount, t.payment_mode, t.status, t.info, t.payee_id, t.category_id, t.memo, t.is_split, t.created_at, t.updated_at, p.name AS payee_name, c.name AS category_name
FROM transactions t
LEFT JOIN payees p ON p.id = t.payee_id
LEFT JOIN categories c ON c.id = t.category_id
WHERE t.account_id = ?
ORDER BY t.date DESC, t.id DESC
LIMIT ? OFFSET ?
`

type ListTransactionsForAccountParams struct {
	AccountID int64
	Limit     int64
	Offset    int64
}

type ListTransactionsForAccountRow struct {
	ID           int64
	WalletID     int64
	AccountID    int64
	Date         string
	Amount       int64
	PaymentMode  int64
	Status       int64
	Info         string
	PayeeID      sql.NullInt64
	CategoryID   sql.NullInt64
	Memo         string
	IsSplit      int64
	CreatedAt    string
	UpdatedAt    string
	PayeeName    sql.NullString
	CategoryName sql.NullString
}

func (q *Queries) ListTransactionsForAccount(ctx context.Context, arg ListTransactionsForAccountParams) ([]ListTransactionsForAccountRow, error) {
	rows, err := q.db.QueryContext(ctx, listTransactionsForAccount, arg.AccountID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTransactionsForAccountRow{}
	for rows.Next() {
		var i ListTransactionsForAccountRow
		if err := rows.Scan(
			&i.ID,
			&i.WalletID,
			&i.AccountID,
			&i.Date,
			&i.Amount,
			&i.PaymentMode,
			&i.Status,
			&i.Info,
			&i.PayeeID,
			&i.CategoryID,
			&i.Memo,
			&i.IsSplit,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PayeeName,
			&i.CategoryName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setTransactionCategory = `-- name: SetTransactionCategory :exec
UPDATE transactions SET
    category_id = ?, updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ?
`

type SetTransactionCategoryParams struct {
	CategoryID sql.NullInt64
	ID         int64
}

func (q *Queries) SetTransactionCategory(ctx context.Context, arg SetTransactionCategoryParams) error {
	_, err := q.db.ExecContext(ctx, setTransactionCategory, arg.CategoryID, arg.ID)
	return err
}

const setTransactionPayee = `-- name: SetTransactionPayee :exec
UPDATE transactions SET
    payee_id = ?, updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ?
`

type SetTransactionPayeeParams struct {
	PayeeID sql.NullInt64
	ID      int64
}

func (q *Queries) SetTransactionPayee(ctx context.Context, arg SetTransactionPayeeParams) error {
	_, err := q.db.ExecContext(ctx, setTransactionPayee, arg.PayeeID, arg.ID)
	return err
}

const setTransactionPaymentMode = `-- name: SetTransactionPaymentMode :exec
UPDATE transactions SET
    payment_mode = ?, updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ?
`

type SetTransactionPaymentModeParams struct {
	PaymentMode int64
	ID          int64
}

func (q *Queries) SetTransactionPaymentMode(ctx context.Context, arg SetTransactionPaymentModeParams) error {
	_, err := q.db.ExecContext(ctx, setTransactionPaymentMode, arg.PaymentMode, arg.ID)
	return err
}

const updateTransaction = `-- name: UpdateTransaction :exec
UPDATE transactions SET
    date = ?, amount = ?, payment_mode = ?, status = ?, info = ?,
    payee_id = ?, category_id = ?, memo = ?, is_split = ?,
    updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ?
`

type UpdateTransactionParams struct {
	Date        string
	Amount      int64
	PaymentMode int64
	Status      int64
	Info        string
	PayeeID     sql.NullInt64
	CategoryID  sql.NullInt64
	Memo        string
	IsSplit     int64
	ID          int64
}

func (q *Queries) UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) error {
	_, err := q.db.ExecContext(ctx, updateTransaction,
		arg.Date,
		arg.Amount,
		arg.PaymentMode,
		arg.Status,
		arg.Info,
		arg.PayeeID,
		arg.CategoryID,
		arg.Memo,
		arg.IsSplit,
		arg.ID,
	)
	return err
}

const updateTransactionStatus = `-- name: UpdateTransactionStatus :exec
UPDATE transactions SET
    status = ?, updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ?
`

type UpdateTransactionStatusParams struct {
	Status int64
	ID     int64
}

func (q *Queries) UpdateTransactionStatus(ctx context.Context, arg UpdateTransactionStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateTransactionStatus, arg.Status, arg.ID)
	return err
}
