// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transfers.sql

package db

import (
	"context"
)

const deleteTransfer = `-- name: DeleteTransfer :exec
DELETE FROM transfers WHERE id = ?
`

func (q *Queries) DeleteTransfer(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTransfer, id)
	return err
}

const getTransfer = `-- name: GetTransfer :one
SELECT id, txn_from_id, txn_to_id FROM transfers WHERE id = ? LIMIT 1
`

func (q *Queries) GetTransfer(ctx context.Context, id int64) (Transfer, error) {
	row := q.db.QueryRowContext(ctx, getTransfer, id)
	var i Transfer
	err := row.Scan(&i.ID, &i.TxnFromID, &i.TxnToID)
	return i, err
}

const getTransferByTransaction = `-- name: GetTransferByTransaction :one
SELECT id, txn_from_id, txn_to_id FROM transfers WHERE txn_from_id = ? OR txn_to_id = ? LIMIT 1
`

type GetTransferByTransactionParams struct {
	TxnFromID int64
	TxnToID   int64
}

func (q *Queries) GetTransferByTransaction(ctx context.Context, arg GetTransferByTransactionParams) (Transfer, error) {
	row := q.db.QueryRowContext(ctx, getTransferByTransaction, arg.TxnFromID, arg.TxnToID)
	var i Transfer
	err := row.Scan(&i.ID, &i.TxnFromID, &i.TxnToID)
	return i, err
}

const insertTransfer = `-- name: InsertTransfer :one
INSERT INTO transfers (txn_from_id, txn_to_id) VALUES (?, ?) RETURNING id, txn_from_id, txn_to_id
`

type InsertTransferParams struct {
	TxnFromID int64
	TxnToID   int64
}

func (q *Queries) InsertTransfer(ctx context.Context, arg InsertTransferParams) (Transfer, error) {
	row := q.db.QueryRowContext(ctx, insertTransfer, arg.TxnFromID, arg.TxnToID)
	var i Transfer
	err := row.Scan(&i.ID, &i.TxnFromID, &i.TxnToID)
	return i, err
}
