// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transfers.sql

package db

import (
	"context"
)

const deleteTransfer = `-- name: DeleteTransfer :exec
DELETE FROM transfers WHERE id = ?
`

func (q *Queries) DeleteTransfer(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTransfer, id)
	return err
}

const getTransfer = `-- name: GetTransfer :one
SELECT id, txn_from_id, txn_to_id FROM transfers WHERE id = ? LIMIT 1
`

func (q *Queries) GetTransfer(ctx context.Context, id int64) (Transfer, error) {
	row := q.db.QueryRowContext(ctx, getTransfer, id)
	var i Transfer
	err := row.Scan(&i.ID, &i.TxnFromID, &i.TxnToID)
	return i, err
}

const getTransferByTransaction = `-- name: GetTransferByTransaction :one
SELECT id, txn_from_id, txn_to_id FROM transfers WHERE txn_from_id = ? OR txn_to_id = ? LIMIT 1
`

type GetTransferByTransactionParams struct {
	TxnFromID int64
	TxnToID   int64
}

func (q *Queries) GetTransferByTransaction(ctx context.Context, arg GetTransferByTransactionParams) (Transfer, error) {
	row := q.db.QueryRowContext(ctx, getTransferByTransaction, arg.TxnFromID, arg.TxnToID)
	var i Transfer
	err := row.Scan(&i.ID, &i.TxnFromID, &i.TxnToID)
	return i, err
}

const insertTransfer = `-- name: InsertTransfer :one
INSERT INTO transfers (txn_from_id, txn_to_id) VALUES (?, ?) RETURNING id, txn_from_id, txn_to_id
`

type InsertTransferParams struct {
	TxnFromID int64
	TxnToID   int64
}

func (q *Queries) InsertTransfer(ctx context.Context, arg InsertTransferParams) (Transfer, error) {
	row := q.db.QueryRowContext(ctx, insertTransfer, arg.TxnFromID, arg.TxnToID)
	var i Transfer
	err := row.Scan(&i.ID, &i.TxnFromID, &i.TxnToID)
	return i, err
}

const listTransfersForWallet = `-- name: ListTransfersForWallet :many
SELECT tr.id, tr.txn_from_id, tr.txn_to_id FROM transfers tr
JOIN transactions t ON t.id = tr.txn_from_id
WHERE t.wallet_id = ?
`

func (q *Queries) ListTransfersForWallet(ctx context.Context, walletID int64) ([]Transfer, error) {
	rows, err := q.db.QueryContext(ctx, listTransfersForWallet, walletID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transfer{}
	for rows.Next() {
		var i Transfer
		if err := rows.Scan(&i.ID, &i.TxnFromID, &i.TxnToID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
