// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: vehicles.sql

package db

import (
	"context"
)

const deleteVehicle = `-- name: DeleteVehicle :exec
DELETE FROM vehicles WHERE id = ?
`

func (q *Queries) DeleteVehicle(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteVehicle, id)
	return err
}

const getVehicle = `-- name: GetVehicle :one
SELECT id, wallet_id, name, plate, notes FROM vehicles WHERE id = ? LIMIT 1
`

func (q *Queries) GetVehicle(ctx context.Context, id int64) (Vehicle, error) {
	row := q.db.QueryRowContext(ctx, getVehicle, id)
	var i Vehicle
	err := row.Scan(
		&i.ID,
		&i.WalletID,
		&i.Name,
		&i.Plate,
		&i.Notes,
	)
	return i, err
}

const insertVehicle = `-- name: InsertVehicle :one
INSERT INTO vehicles (wallet_id, name, plate, notes) VALUES (?, ?, ?, ?) RETURNING id, wallet_id, name, plate, notes
`

type InsertVehicleParams struct {
	WalletID int64
	Name     string
	Plate    string
	Notes    string
}

func (q *Queries) InsertVehicle(ctx context.Context, arg InsertVehicleParams) (Vehicle, error) {
	row := q.db.QueryRowContext(ctx, insertVehicle,
		arg.WalletID,
		arg.Name,
		arg.Plate,
		arg.Notes,
	)
	var i Vehicle
	err := row.Scan(
		&i.ID,
		&i.WalletID,
		&i.Name,
		&i.Plate,
		&i.Notes,
	)
	return i, err
}

const listVehiclesForWallet = `-- name: ListVehiclesForWallet :many
SELECT id, wallet_id, name, plate, notes FROM vehicles WHERE wallet_id = ? ORDER BY name
`

func (q *Queries) ListVehiclesForWallet(ctx context.Context, walletID int64) ([]Vehicle, error) {
	rows, err := q.db.QueryContext(ctx, listVehiclesForWallet, walletID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Vehicle{}
	for rows.Next() {
		var i Vehicle
		if err := rows.Scan(
			&i.ID,
			&i.WalletID,
			&i.Name,
			&i.Plate,
			&i.Notes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateVehicle = `-- name: UpdateVehicle :exec
UPDATE vehicles SET name = ?, plate = ?, notes = ? WHERE id = ?
`

type UpdateVehicleParams struct {
	Name  string
	Plate string
	Notes string
	ID    int64
}

func (q *Queries) UpdateVehicle(ctx context.Context, arg UpdateVehicleParams) error {
	_, err := q.db.ExecContext(ctx, updateVehicle,
		arg.Name,
		arg.Plate,
		arg.Notes,
		arg.ID,
	)
	return err
}
