// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: wallets.sql

package db

import (
	"context"
	"database/sql"
)

const addWalletMember = `-- name: AddWalletMember :exec
INSERT INTO wallet_members (wallet_id, user_id, role)
VALUES (?, ?, ?)
`

type AddWalletMemberParams struct {
	WalletID int64
	UserID   int64
	Role     string
}

func (q *Queries) AddWalletMember(ctx context.Context, arg AddWalletMemberParams) error {
	_, err := q.db.ExecContext(ctx, addWalletMember, arg.WalletID, arg.UserID, arg.Role)
	return err
}

const createWallet = `-- name: CreateWallet :one
INSERT INTO wallets (title, owner_name)
VALUES (?, ?)
RETURNING id, title, owner_name, base_currency_id, settings_json, created_at
`

type CreateWalletParams struct {
	Title     string
	OwnerName string
}

func (q *Queries) CreateWallet(ctx context.Context, arg CreateWalletParams) (Wallet, error) {
	row := q.db.QueryRowContext(ctx, createWallet, arg.Title, arg.OwnerName)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.OwnerName,
		&i.BaseCurrencyID,
		&i.SettingsJson,
		&i.CreatedAt,
	)
	return i, err
}

const deleteWallet = `-- name: DeleteWallet :exec
DELETE FROM wallets WHERE id = ?
`

func (q *Queries) DeleteWallet(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteWallet, id)
	return err
}

const getWallet = `-- name: GetWallet :one
SELECT id, title, owner_name, base_currency_id, settings_json, created_at FROM wallets WHERE id = ? LIMIT 1
`

func (q *Queries) GetWallet(ctx context.Context, id int64) (Wallet, error) {
	row := q.db.QueryRowContext(ctx, getWallet, id)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.OwnerName,
		&i.BaseCurrencyID,
		&i.SettingsJson,
		&i.CreatedAt,
	)
	return i, err
}

const getWalletMembership = `-- name: GetWalletMembership :one
SELECT role FROM wallet_members WHERE wallet_id = ? AND user_id = ? LIMIT 1
`

type GetWalletMembershipParams struct {
	WalletID int64
	UserID   int64
}

func (q *Queries) GetWalletMembership(ctx context.Context, arg GetWalletMembershipParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getWalletMembership, arg.WalletID, arg.UserID)
	var role string
	err := row.Scan(&role)
	return role, err
}

const listAllWalletIDs = `-- name: ListAllWalletIDs :many
SELECT id FROM wallets ORDER BY id
`

func (q *Queries) ListAllWalletIDs(ctx context.Context) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listAllWalletIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWalletsForUser = `-- name: ListWalletsForUser :many
SELECT w.id, w.title, w.owner_name, w.base_currency_id, w.settings_json, w.created_at, m.role AS member_role
FROM wallets w
JOIN wallet_members m ON m.wallet_id = w.id
WHERE m.user_id = ?
ORDER BY w.title
`

type ListWalletsForUserRow struct {
	ID             int64
	Title          string
	OwnerName      string
	BaseCurrencyID sql.NullInt64
	SettingsJson   string
	CreatedAt      string
	MemberRole     string
}

func (q *Queries) ListWalletsForUser(ctx context.Context, userID int64) ([]ListWalletsForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listWalletsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWalletsForUserRow{}
	for rows.Next() {
		var i ListWalletsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.OwnerName,
			&i.BaseCurrencyID,
			&i.SettingsJson,
			&i.CreatedAt,
			&i.MemberRole,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWallet = `-- name: UpdateWallet :exec
UPDATE wallets SET title = ?, owner_name = ? WHERE id = ?
`

type UpdateWalletParams struct {
	Title     string
	OwnerName string
	ID        int64
}

func (q *Queries) UpdateWallet(ctx context.Context, arg UpdateWalletParams) error {
	_, err := q.db.ExecContext(ctx, updateWallet, arg.Title, arg.OwnerName, arg.ID)
	return err
}
