// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: walletref.sql

package db

import (
	"context"
	"strings"
)

const countAccountsInWallet = `-- name: CountAccountsInWallet :one

SELECT COUNT(*) FROM accounts WHERE wallet_id = ?1 AND id IN (/*SLICE:ids*/?)
`

type CountAccountsInWalletParams struct {
	WalletID int64
	Ids      []int64
}

// Ownership checks for the ids a request names (#543): each counts how many of
// the given ids are rows of the wallet.
func (q *Queries) CountAccountsInWallet(ctx context.Context, arg CountAccountsInWalletParams) (int64, error) {
	query := countAccountsInWallet
	var queryParams []interface{}
	queryParams = append(queryParams, arg.WalletID)
	if len(arg.Ids) > 0 {
		for _, v := range arg.Ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(arg.Ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	row := q.db.QueryRowContext(ctx, query, queryParams...)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countCategoriesInWallet = `-- name: CountCategoriesInWallet :one
SELECT COUNT(*) FROM categories WHERE wallet_id = ?1 AND id IN (/*SLICE:ids*/?)
`

type CountCategoriesInWalletParams struct {
	WalletID int64
	Ids      []int64
}

func (q *Queries) CountCategoriesInWallet(ctx context.Context, arg CountCategoriesInWalletParams) (int64, error) {
	query := countCategoriesInWallet
	var queryParams []interface{}
	queryParams = append(queryParams, arg.WalletID)
	if len(arg.Ids) > 0 {
		for _, v := range arg.Ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(arg.Ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	row := q.db.QueryRowContext(ctx, query, queryParams...)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPayeesInWallet = `-- name: CountPayeesInWallet :one
SELECT COUNT(*) FROM payees WHERE wallet_id = ?1 AND id IN (/*SLICE:ids*/?)
`

type CountPayeesInWalletParams struct {
	WalletID int64
	Ids      []int64
}

func (q *Queries) CountPayeesInWallet(ctx context.Context, arg CountPayeesInWalletParams) (int64, error) {
	query := countPayeesInWallet
	var queryParams []interface{}
	queryParams = append(queryParams, arg.WalletID)
	if len(arg.Ids) > 0 {
		for _, v := range arg.Ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(arg.Ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	row := q.db.QueryRowContext(ctx, query, queryParams...)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTemplatesInWallet = `-- name: CountTemplatesInWallet :one
SELECT COUNT(*) FROM templates WHERE wallet_id = ?1 AND id IN (/*SLICE:ids*/?)
`

type CountTemplatesInWalletParams struct {
	WalletID int64
	Ids      []int64
}

func (q *Queries) CountTemplatesInWallet(ctx context.Context, arg CountTemplatesInWalletParams) (int64, error) {
	query := countTemplatesInWallet
	var queryParams []interface{}
	queryParams = append(queryParams, arg.WalletID)
	if len(arg.Ids) > 0 {
		for _, v := range arg.Ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(arg.Ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	row := q.db.QueryRowContext(ctx, query, queryParams...)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countVehiclesInWallet = `-- name: CountVehiclesInWallet :one
SELECT COUNT(*) FROM vehicles WHERE wallet_id = ?1 AND id IN (/*SLICE:ids*/?)
`

type CountVehiclesInWalletParams struct {
	WalletID int64
	Ids      []int64
}

func (q *Queries) CountVehiclesInWallet(ctx context.Context, arg CountVehiclesInWalletParams) (int64, error) {
	query := countVehiclesInWallet
	var queryParams []interface{}
	queryParams = append(queryParams, arg.WalletID)
	if len(arg.Ids) > 0 {
		for _, v := range arg.Ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(arg.Ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	row := q.db.QueryRowContext(ctx, query, queryParams...)
	var count int64
	err := row.Scan(&count)
	return count, err
}
